### ISSUE TITLE
libMesh does not compile with --disable-exceptions

### ISSUE THREAD

**Issue by jwpeterson** [libMesh/libmesh#1034]
There's several things which aren't ifdef'd properly...

Before I fix that, though, I'd like to know whether this ifdef was meant to be for supporting compilers which don't have exceptions (no exist that I know of), or merely for controlling the behavior of the `LIBMESH_THROW` macro.  That is, should we just feel free to use `try`/`catch` blocks without wrapping them?

**Comment by roystgnr** [comment]
The --disable-rtti ifdefs were for compiler support, IIRC, but exception-disabling wasn't.  If we really want to support exceptionless compilation I'd say create libmesh_try and libmesh_catch (the former would be '' and the later 'if (0)' in the fallback case) rather than forcing ifdefs everywhere.

IIRC the only reason to support exceptionless compilation was that not every ABI supports zero-overhead in the no-exception-thrown case, and people may want to turn off exceptions when their very existence costs.  That's not really a factor since the death of Win32, though, and even when exception support got turned off I don't think that turned off support for exception syntax.
