### ISSUE TITLE
Segfault with complex-enabled DenseMatrix::svd()

### ISSUE THREAD

**Issue by jwpeterson** [libMesh/libmesh#1043]
The following simple test case can be used to reproduce the segfault on an `--enable-complex` build:

```
int main (int argc, char** argv)
{
  LibMeshInit init (argc, argv);
  DenseMatrix< Complex > A(3,3);

  A(0,0) = Complex(2.18904,4.44523e-18); A(0,1) = Complex(-3.20491,-0.136699);   A(0,2) = Complex(0.716316,-0.964802);
  A(1,0) = Complex(-3.20491,0.136699);   A(1,1) = Complex(4.70076,-3.25261e-18); A(1,2) = Complex(-0.98849,1.45727);
  A(2,0) = Complex(0.716316,0.964802);   A(2,1) = Complex(-0.98849,-1.45727);    A(2,2) = Complex(0.659629,-4.01155e-18);

  std::cout << "A = " << std::endl << A << std::endl;
  DenseVector< Real > sigma;
  A.svd( sigma );
  std::cout << "sigma = " << std::endl << sigma << std::endl;

  return 0;
}
```

@dknez has investigated this a bit and determined that the problem may be related to LAPACK clearing the "number_val" array.

**Comment by dknez** [comment]
I tried malloc/free and it didn't help. I'm not sure what's happening here... very confusing to me. If you could have a look, that'd be most appreciated.

This page is helpful for info about the LAPACK routine (the same info is copied into the libMesh source code):
http://www.netlib.org/lapack/lapack-3.1.1/html/dgesvd.f.html

Note that it says:
*          if JOBU .ne. 'O' and JOBVT .ne. 'O', the contents of A
*                          are destroyed.
We do not use 'O', so it looks like A is indeed destroyed. This seems like a bug in our svd code because we potentially destroy the DenseMatrix's _val array.

Another potential issue is that we pass in _val, which is row-major, but I presume LAPACK requires column major.

Seems like a few things need to be cleaned up here...

**Comment by dknez** [comment]
Something else I wanted to check. In _svd_lapack we call
_svd_helper(JOBU, JOBVT, sigma_val, VT.get_values(), U.get_values());
but the VT, U order doesn't match the arguments in _svd_helper.

**Comment by dknez** [comment]
This page is also helpful:
http://www.ibm.com/support/knowledgecenter/SSFHY8_5.4.0/com.ibm.cluster.essl.v5r4.essl100.doc/am5gr_hgesvd.htm

One thing is that it says that RWORK should be at least 5*min(m,n). I tried that but that didn't fix the segfault for me.

**Comment by jwpeterson** [comment]
> On Jul 29, 2016, at 8:34 PM, David Knezevic <notifications@github.com> wrote:
> 
> Something else I wanted to check. In _svd_lapack we call
> _svd_helper(JOBU, JOBVT, sigma_val, VT.get_values(), U.get_values());
> but the VT, U order doesn't match the arguments in _svd_helper.
> 

Right, check the commit history, I think it explains why that's done.  The column major issue is also taken care of by flipping the arguments, since (USV^T) = VSU^T.

**Comment by jwpeterson** [comment]
> On Jul 30, 2016, at 8:26 AM, John Peterson <jwpeterson@gmail.com> wrote:
> 
> 
> 
>> On Jul 29, 2016, at 8:34 PM, David Knezevic <notifications@github.com> wrote:
>> 
>> Something else I wanted to check. In _svd_lapack we call
>> _svd_helper(JOBU, JOBVT, sigma_val, VT.get_values(), U.get_values());
>> but the VT, U order doesn't match the arguments in _svd_helper.
>> 
> 
> Right, check the commit history, I think it explains why that's done.  The column major issue is also taken care of by flipping the arguments, since (USV^T) = VSU^T.

Sorry, should have been an extra transpose on the left hand side...


> (USV^T)^T = VSU^T

**Comment by dknez** [comment]
OK, thanks for the explanation re the order of the U and VT arguments and the transpose issue, that makes sense.

Regarding the segfault: I figured out what was wrong. I had to consult the documentation for the complex version of LAPACK's svd routine, zgesvd:
http://www.netlib.org/lapack/explore-3.1.1-html/zgesvd.f.html

There it explains how to set RWORK properly, and if I follow that with "std::vector<Real> RWORK(5 * min_MN);" then it works fine. I'll make a PR with this fix.

I'll also change it so that we call the SVD routine on a copy of _val in the real case as well to make sure that _val doesn't get cleared.

**Comment by jwpeterson** [comment]
> On Jul 30, 2016, at 3:26 PM, David Knezevic <notifications@github.com> wrote:
> 
> OK, thanks for the explanation re the order of the U and VT arguments and the transpose issue, that makes sense.
> 
> Regarding the segfault: I figured out what was wrong. I had to consult the documentation for the complex version of LAPACK's svd routine, zgesvd:
> http://www.netlib.org/lapack/explore-3.1.1-html/zgesvd.f.html
> 
> There it explains how to set RWORK properly, and if I follow that with "std::vector RWORK(5 * min_MN);" then it works fine. I'll make a PR with this fix.
> 
> I'll also change it so that we call the SVD routine on a copy of _val in the real case as well to make sure that _val doesn't get cleared.
> 
It's too bad if we really have to do that extra copy.  How do you interpret "destroyed"?  I always thought it meant "overwritten" and not freed in the context of Lapack docs.  I.e. that the algorithm uses it for work space so you can't rely on the values after calling the function...

**Comment by dknez** [comment]
You're probably right that it just means that the values may be overwritten. I don't know for sure though... if you're a masochist you can read the fortran code at the netlib links I gave above :)

I need to have the copy in the complex-valued case anyway because in that case _val may contain Reals but we need to pass in Complex's to the lapack SVD routine since PETSc is configured to use zgesvd rather than dgesvd in that case.

But if you like, I can keep the real-valued case how it was before, i.e. without the copy. Let me know what you prefer.

**Comment by dknez** [comment]
I made a PR. I did not make the copy in the real-valued case, as you suggested.

**Comment by jwpeterson** [comment]
> On Jul 30, 2016, at 4:03 PM, David Knezevic <notifications@github.com> wrote:
> 
> I made a PR. I did not make the copy in the real-valued case, as you suggested.
> 

Thanks!  Yeah, let's keep the real-valued case as-is unless we run across a nasty Lapack implementation that actually frees _val.  

I do agree that users of svd() are probably making this copy themselves in most cases because they need to do something else with the matrix, but I'd rather not force everyone to pay for a copy if they don't have to.

**Comment by dknez** [comment]
Agreed.

**Comment by dknez** [comment]
I merged the PR, so I'm closing this issue.

**Comment by boyceg** [comment]
> On Jul 30, 2016, at 5:44 PM, John W. Peterson <notifications@github.com> wrote:
> 
> 
> 
> > On Jul 30, 2016, at 3:26 PM, David Knezevic <notifications@github.com> wrote:
> > 
> > OK, thanks for the explanation re the order of the U and VT arguments and the transpose issue, that makes sense.
> > 
> > Regarding the segfault: I figured out what was wrong. I had to consult the documentation for the complex version of LAPACK's svd routine, zgesvd:
> > http://www.netlib.org/lapack/explore-3.1.1-html/zgesvd.f.html
> > 
> > There it explains how to set RWORK properly, and if I follow that with "std::vector RWORK(5 * min_MN);" then it works fine. I'll make a PR with this fix.
> > 
> > I'll also change it so that we call the SVD routine on a copy of _val in the real case as well to make sure that _val doesn't get cleared.
> > 
> It's too bad if we really have to do that extra copy. How do you interpret "destroyed"? I always thought it meant "overwritten" and not freed in the context of Lapack docs. I.e. that the algorithm uses it for work space so you can't rely on the values after calling the function…

Pure Fortran 77 doesn’t support dynamic memory allocation/deallocation — I think they mean “overwritten” here.

**Comment by dknez** [comment]
OK, good to know, thanks!
