### ISSUE TITLE
Terminate Warning with GCC 6.1

### ISSUE THREAD

**Issue by pbauman** [libMesh/libmesh#1073]
I'm seeing the following with the current master and GCC 6.1. Sorry I don't have time to look into it, but I at least wanted to log it.

<pre>
In file included from ./include/libmesh/libmesh_common.h:59:0,
                 from ./include/libmesh/libmesh.h:25,
                 from ../../pbauman/src/base/libmesh.C:20:
../../pbauman/src/base/libmesh.C: In destructor ‘virtual libMesh::LibMeshInit::~LibMeshInit()’:
./include/libmesh/libmesh_common.h:366:39: warning: throw will always call terminate() [-Wterminate]
     LIBMESH_THROW(libMesh::LogicError());                               \
                                       ^
./include/libmesh/libmesh_exceptions.h:150:37: note: in definition of macro ‘LIBMESH_THROW’
 #define LIBMESH_THROW(e) do { throw e; } while (0)
                                     ^
./include/libmesh/libmesh_common.h:288:7: note: in expansion of macro ‘libmesh_error_msg’
       libmesh_error_msg(msg);                                           \
       ^~~~~~~~~~~~~~~~~
./include/libmesh/libmesh_common.h:342:34: note: in expansion of macro ‘libmesh_assert_msg’
 #define libmesh_assert(asserted) libmesh_assert_msg(asserted, "")
                                  ^~~~~~~~~~~~~~~~~~
./include/libmesh/parallel.h:58:5: note: in expansion of macro ‘libmesh_assert’
     libmesh_assert((comm_obj).verify(std::string(__FILE__).size()));    \
     ^~~~~~~~~~~~~~
../../pbauman/src/base/libmesh.C:642:3: note: in expansion of macro ‘libmesh_parallel_only’
   libmesh_parallel_only(this->comm());
   ^~~~~~~~~~~~~~~~~~~~~
./include/libmesh/libmesh_common.h:366:39: note: in C++11 destructors default to noexcept
     LIBMESH_THROW(libMesh::LogicError());                               \
                                       ^
./include/libmesh/libmesh_exceptions.h:150:37: note: in definition of macro ‘LIBMESH_THROW’
 #define LIBMESH_THROW(e) do { throw e; } while (0)
                                     ^
./include/libmesh/libmesh_common.h:288:7: note: in expansion of macro ‘libmesh_error_msg’
       libmesh_error_msg(msg);                                           \
       ^~~~~~~~~~~~~~~~~
./include/libmesh/libmesh_common.h:342:34: note: in expansion of macro ‘libmesh_assert_msg’
 #define libmesh_assert(asserted) libmesh_assert_msg(asserted, "")
                                  ^~~~~~~~~~~~~~~~~~
./include/libmesh/parallel.h:58:5: note: in expansion of macro ‘libmesh_assert’
     libmesh_assert((comm_obj).verify(std::string(__FILE__).size()));    \
     ^~~~~~~~~~~~~~
../../pbauman/src/base/libmesh.C:642:3: note: in expansion of macro ‘libmesh_parallel_only’
   libmesh_parallel_only(this->comm());
</pre>

**Comment by roystgnr** [comment]
The warning makes sense (we're potentially throwing an exception from within a destructor, which kills the program), but I don't know what we'd want to do differently.  If the user's code's different ranks are in sync, then the exception won't be thrown.  If they're out of sync, then really the best we can hope for is to die immediately with an informative error message.

**Comment by jwpeterson** [comment]
> throwing an exception from within a destructor, which kills the program),

Isn't it actually [undefined behavior](http://stackoverflow.com/questions/130117/throwing-exceptions-out-of-a-destructor) to throw from a desctructor?  Which, yes, could kill the program but could also do anything else...


I'm impressed that compiler can detect (presumably in debug mode only?) the following chain of function calls:
```
~LibMeshInit -> libmesh_parallel_only() -> libmesh_assert -> libmesh_error_msg -> LIBMESH_THROW
```
Should we maybe add a "no throw" version of the `libmesh_parallel_only()` macro?  I don't know of anywhere in the library that would currently catch such an exception anyway, but I suppose there is always app code... otherwise, seems like a good candidate for libmesh/ignore_warnings.h.

**Comment by roystgnr** [comment]
No, not undefined behavior.  In the C++03 standard, sections 15.2 and 15.5.1 make it clear that an exception which escapes a destructor results in an immediate call to std::terminate().

In C++11 it's even a bit looser, as best as I can tell: if you override the default "noexcept" specification on your destructor, *and* your destructor isn't currently being called as part of stack unwinding during another exception throw, *and* the object being destroyed isn't static or TLS, then the exception is allowed to propagate and be handled normally; otherwise you get std::terminate().

Nitpicking aside, though, after a little more thought my vote is to just remove the libmesh_parallel_only() macro call here.  The hypothetical advantage of maybe being able to more easily debug MPI sync failures at LibMeshInit destruction time isn't worth the definite annoyance of a false positive warning or of trying to work around the warning.

**Comment by permcody** [comment]
On Thu, Aug 25, 2016 at 9:49 AM roystgnr <notifications@github.com> wrote:

> No, not undefined behavior. In the C++03 standard, sections 15.2 and
> 15.5.1 make it clear that an exception which escapes a destructor results
> in an immediate call to std::terminate().
>
> In C++11 it's even a bit looser, as best as I can tell: if you override
> the default "noexcept" specification on your destructor, *and* your
> destructor isn't currently being called as part of stack unwinding during
> another exception throw, *and* the object being destroyed isn't static or
> TLS, then the exception is allowed to propagate and be handled normally;
> otherwise you get std::terminate().
>

I'll throw in (no pun intended) my experience with "noexcept" since it's
slightly relevant here. One needs to carefully think about noexcept when
overriding certain class members. AFAIK a user defined destructor is
noexcept even when missing the noexcept expression unless a base member
destructor is NOT noexcept. However, the opposite is true for user-defined
move constructors and move assignment operators (the compiler default is
noexcept but not if you supply the definition yourself). I previously
posted a gist that shows how your performance can really go into the toilet
if you fail to use the noexcept keyword with the two "move" definitions and
use your class directly in some containers (such as std::vector) since
noexcept is required to ensure the strong exception guarantee.

Anyway, I know this is tangent to Roy's response but still very important
to understand.

Cody
