### ISSUE TITLE
large errors in InfFE::inverse_map()

### ISSUE THREAD

**Issue by BalticPinguin** [libMesh/libmesh#1084]
Hi all,
as discussed in my PR yesterday, here is a description of the error in the inverse_map()/map() function.
As code example I use miscellaneous_ex1.C and added a function map_remap() that runs over the quadrature points and prints them together with the map(inverse_map()) of them.
In addition, I have the output I get for it in two versions: First (Interpol.out) as you will get it from the current libMesh version and in the second one I enforced interpolated=false in InfFE::inverse_map() (src/fe/inf_fe_map.C:108).
Code and output in the gist:
https://gist.github.com/BalticPinguin/09e4b3090a87d4c5d8af15255b1fd8dc

**Comment by BalticPinguin** [comment]
So as I see it, the default scheme used to obtain the 3-rd component gives large errors, while the scheme with Newton iteration works quite well. 
As I see it (without having had a closer look at the math in there), there are several things that should be changed:
1. First, I would uncomment the warnings (l. 415ff and 597ff in src/fe/inf_fe_map.C) such that the user at least has a chance to see that there is an error.
2. At least through the FEInterface-class, one can not govern the parameter interpolated so one is forced to use the default. Hence, I would either change the defaults or the FEInterface interface.
3. If I find time in the next days, I can try to dig into the maths of the inverse_map() with interpolated==true and see why the errors come up (numerically instable or what else).

What do you think about it?
Best,
Hubert

**Comment by jwpeterson** [comment]
> 1 -0.77621  -0.77621  -1.0349   -0.75981  -0.75981  -1.0131

I'd say the error is unacceptably high in every component (I am just looking at the first three floats vs. the last three on each line, not sure exactly what you meant by "3-rd component") for the current default algorithm, while the Newton algorithm looks fine.  Not to mention that the current default algorithm also asserts on one of the points:

> 1 -0.25874  -0.25874  -1.0349   Assertion `-1.-1.e-5 <= v && v < 1.' failed.

I'd definitely change the default algorithm to not use interpolation, as it is just wrong... Do you know whether the bug is restricted to `map` or `inverse_map`, or if both are wrong?

**Comment by jwpeterson** [comment]
> Do you know whether the bug is restricted to map or inverse_map, or if both are wrong?

Never mind this question, after I looked at the code a bit more, the `interpolated` stuff is restricted to the `inverse_map` function, so that must be where the error is.  Looking at the `interpolated==true` code branch, I don't really suspect a bug per se, as the calculation itself appears to be very simple... I think it is just an inaccurate (but fast) way of computing the inverse map, and should probably be avoided if something like `map_remap()` is important to you.  Also, I'd reiterate that it should also not be the default.

By the way, I fixed several deprecated `Point::size()` calls in `InfFE::inverse_map()` so make sure to pull the latest version if you make changes here as well.

**Comment by BalticPinguin** [comment]
ok, that sounds good to me. 
In my comment I was a bit unclear, you are right. with '3-rd component' I meant the z-component of the reference point.  And that assertion you mentioned above is due to the reference point being not in the reference element.

An other question is whether one wants to leave the 'interpolated==true' algorithm if it is known to be inaccurate...

**Comment by jwpeterson** [comment]
> An other question is whether one wants to leave the 'interpolated==true' algorithm if it is known to be inaccurate...

I'd be OK with removing it entirely.

**Comment by jwpeterson** [comment]
Fixed by #1085.
