### ISSUE TITLE
Fails to build with 64bit indices blas

### ISSUE THREAD

**Issue by canesin** [libMesh/libmesh#1187]
Hi,

In newer OpenBLAS and Intel MKL it is possible to have 64 indices, PETSc added the option:
--known-64-bit-blas-indices=true \
To live with that, when this flag is true PetscBLASInt is defined to long (on clang) and LibMesh will fail to compile the BLAS wrapper code in src/numerics/dense_matrix_blas_lapack.C

```
src/numerics/dense_matrix_blas_lapack.C:1147:34: note: in instantiation of member function 'libMesh::DenseMatrix<double>::_evd_lapack' requested here
template void DenseMatrix<Real>::_evd_lapack(DenseVector<Real> &,
                                 ^
/opt/petsc/include/petscblaslapack.h:150:19: note: candidate function not viable: no known conversion from 'int *' to 'PetscBLASInt *' (aka 'long *') for 3rd argument
PETSC_EXTERN void LAPACKgeev_(const char*,const char*,PetscBLASInt *,PetscScalar *,PetscBLASInt*,PetscReal*,PetscReal*,PetscScalar*,PetscBLASInt*,PetscScalar*,PetscBLASInt*,PetscScalar*,PetscBLASInt*,PetscBLASInt*);
                  ^
```

**Comment by jwpeterson** [comment]
Seems like this should be fixed if we declare all of the integer types in dense_matrix_blas_lapack.C as `PetscBLASInt`, right?  I will try and check what version of PETSc this type was first introduced so we can guard it properly as well.  Since I don't have a 64-bit indices BLAS readily-available, would you be able to test out the PR on your system?

**Comment by jwpeterson** [comment]
>  I will try and check what version of PETSc this type was first introduced so we can guard it properly as well.

`PetscBLASInt` has been around since 2.3.2 so there's no need to guard its use.
