### ISSUE TITLE
Support hyphenated versions of all long command line options

### ISSUE THREAD

**Issue by jwpeterson** [libMesh/libmesh#1269]
We are pretty consistent about this already, but there are a few non-conforming flags like `--node_major_dofs`, `--solver_system_names`, `--solver_variable_names`, `--implicit_neighbor_dofs`, `--read_ifem_systems`, etc. that use an underscore for the separator, which is a bit inconsistent.  Basically we should make all these like `--print-trace`, which already supports both underscore and hyphenated versions.

**Comment by roystgnr** [comment]
Hmm... about half of those are mine, and are probably artifacts of the thought process "I'm programming in C++, and you can't put a dash in a C++ identifier, so you shouldn't put a dash in an option name"... but https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html says the convention is "alphanumeric characters and dashes" for long options and so we should definitely support that.

It might be reasonable to make a little utility function that checks both versions rather than using the print-trace || print_trace style logic every time.

**Comment by jwpeterson** [comment]
> a little utility function

Good idea.
