### ISSUE TITLE
Take advantage of other Mat types in PETSc 

### ISSUE THREAD

**Issue by jwpeterson** [libMesh/libmesh#1385]
We currently build `PetscMatrix` objects with underlying `MATAIJ` and `MATBAIJ` types in LibMesh, but there are other types, including `MATHYPRE` (petsc/petsc@63c07aad33d943fe85193412d077a1746a7c55aa) which (I assume) could save quite a bit of memory for people who are using BoomerAMG as a preconditioner/solver. Based on the relevant [PETSc example](https://github.com/petsc/petsc/blob/master/src/mat/examples/tests/ex115.c), one also needs to call the appropriate preallocation function (`MatHYPRESetPreallocation`) and there may be some other limitations:
```
/* HYPRE_IJMatrix does not support INSERT_VALUES with off-proc entries */
```
```
/* MatAXPY_Basic further exercises MatSetValues_HYPRE */
      /* however there are still some issues
         with rectangular matrices.
         try, e.g., mpiexec -n 3 ./ex115 -M 7 -N 6 -test_rectangular */
```
so this needs further investigation.

@fdkong will be looking into this in the somewhat near future.

**Comment by jwpeterson** [comment]
@roystgnr I think @fdkong is going to be taking a closer look at this soon. We were wondering what the best/cleanest approach for adding another matrix type would be. This information somehow needs to be available when `PetscMatrix::init()` is called. For the `MATBAIJ` type we handled it by passing in a `blocksize` but that doesn't generalize well to other matrix types. 

We could 

* Add yet another default parameter to `init()` or the `SparseMatrix` constructor.
* Add a virtual `set_matrix_type()` method that users could call in between construction and `init()` time.
* Other ideas?

**Comment by roystgnr** [comment]
I don't like the default parameter idea, although I really can't give more of an argument than "aesthetic reasons", so feel free to override.  But the only disadvantage of a set_matrix_type() method is that it requires the work of constructing to be deferred, and since we *already* defer until init() we might as well gain some advantage from that.

The only thing I'd consider adding on top of set_matrix_type() would be a set_default_matrix_type(), to affect SparseMatrix::build() in general.  That would mean translating in between PETSc types and SomeHokeyLibMeshEnum which is an embarrassingly obvious shim to PETSc types, but it would mean that you could just set your preference once and then get it thereafter for the ImplicitSystem matrix, the multiple NewmarkSystem matrices, any user-added preconditioner matrices, everything.

**Comment by jwpeterson** [comment]
> The only thing I'd consider adding on top of set_matrix_type() would be a set_default_matrix_type(), to affect SparseMatrix::build() in general.

Yeah, this is a good idea. I was worried about having to find every place that a SparseMatrix was created and adding a set_matrix_type() call, but if we can figure out a way to have a default that's set once and inherited by every instance of the class (SparseMatrix class static variable?) that would definitely mitigate the problem.

**Comment by roystgnr** [comment]
Static variable was what I had in mind, yeah.

And if you were thinking about using SparseMatrix::set_matrix_type() in library code, that means we would have to create SomeHokeyEnum *regardless* (as opposed to only creating a PetscMatrix::set_matrix_type() API), at which point adding a set_default_matrix_type() would be trivial.
