### ISSUE TITLE
Make it easier to control quadrature order in a FEMContext

### ISSUE THREAD

**Issue by dknez** [libMesh/libmesh#1397]
I gather that to set the quadrature order in a FEMContext to something other than the default, we have to set System::extra_quadrature_order.

In some cases, in particular in structural analysis where reduced integration is common, I'd like to have more control over the quadrature order.

In particular, it's currently not easy for me to use a "1-point" quadrature rule since I would first have to compute which order would be used (e.g. by mimicking the code in the FEMContext constructor), and then set extra_quadrature_order based on that.

Also, it'd be nice to be able to set different quadrature orders per dimension.

Would an update to FEMContext to facilitate this be of interest? Perhaps we could add a new constructor that allows the user to set the quadrature order for each dimension, rather than using System::extra_quadrature_order?

**Comment by roystgnr** [comment]
This would definitely be a good feature to add.  Seems straightforward, too; the only question I can see is "Does FEMContext store an extra_quadrature_order which defaults to System::extra_quadrature_order, or does FEMContext store an extra_extra_quadrature_order which defaults to 0".  I'd lean toward the former but they're isomorphic so either way seems fine.

**Comment by dknez** [comment]
OK, I'll look into a PR for this.

Regarding your question: I'd rather pass in the desired quadrature order, not the extra_quadrature_order, since that way I could just set the order without having to worry about what the default would have been. Also I guess we don't need to store anything extra since we can get the quadrature orders from the qrule objects. I guess you had something else in mind though?

**Comment by roystgnr** [comment]
There's no such thing as *the* desired quadrature order, in general, though - there's a different desired quadrature order for each variable.  Usually the quadrature order we want is related to the variable polynomial degree, so then tweaking that up or down a little from the baseline is "good enough"... but if we want an interface to set absolute quadrature order rather than relative, I don't think a single value is going to be good enough for that interface...

**Comment by dknez** [comment]
I don't disagree with you, but my motivation here was indeed to be able set the absolute quadrature order rather than relative. This makes sense if I want a 1-point quadrature rule, for example, since there I just want to set the order without worrying about what the default would have been for the "hardest" FE variable in the system.

If you don't want absolute orders in the FEMContext API, then I'll just drop this issue and do something else in my code. Let me know what you think.

**Comment by roystgnr** [comment]
Huh, no, you're right.  Even though we *desire* a different quadrature order for each variable, we only end up *using* a single order, since we can't efficiently use differing orders without any a priori knowledge about which variables are going to be integrated by which other variables.  And so setting a single absolute value for that final quadrature order makes sense.  Go ahead.

**Comment by dknez** [comment]
OK, I'll put something together and see how it looks...

**Comment by jwpeterson** [comment]
Fixed in #1399.
