### ISSUE TITLE
Error when writing then reading an xdr

### ISSUE THREAD

**Issue by dknez** [libMesh/libmesh#1434]
Add the following code into introduction_ex4.C after mesh.print_info();

```
  mesh.write("mesh.xdr");
  Mesh new_mesh(init.comm(), 3);
  new_mesh.read("mesh.xdr");
```

For me, this gives the following error:
```
Assertion `pos+Elem::type_to_n_nodes_map[input_buffer[0]] < input_buffer.size()' failed.
pos+Elem::type_to_n_nodes_map[input_buffer[0]] = 1952456820
input_buffer.size() = 100
```

@roystgnr I guess this is related to 48a92965 ?

**Comment by roystgnr** [comment]
Damn it, almost certainly.  Would you let me know what OS you're on, and what the various id_type lengths are set to?

**Comment by roystgnr** [comment]
I can't seem to reproduce the failure on Linux x86_64 with --enable-everything and the default type lengths.

**Comment by dknez** [comment]
I'm on Ubuntu 16.04. I can check the id_type lengths shortly.

**Comment by roystgnr** [comment]
And I *thought* we had test coverage of XDR reads.  Not *good enough* test coverage, and I'm working on that, but it looks like adaptivity_ex5 and miscellaneous_ex12 both read just-written xdr files!

**Comment by roystgnr** [comment]
It'd also be good to know whether you have unique_id enabled.

**Comment by roystgnr** [comment]
Gah, I can't reproduce the failure with unique_id disabled or with it enabled.

**Comment by roystgnr** [comment]
Could you send me the failing mesh.xdr?  I can at least try to figure out whether something's going wrong with writes or with reads.

**Comment by dknez** [comment]
My configuration is below:

```
configure --enable-everything --enable-slepc --with-metis=PETSc --with-subdomain-id-bytes=4 --with-boundary-id-bytes=4 --disable-glpk --enable-unique-id --with-unique-id-bytes=4 --with-nlopt-include=/home/dknez/software/libmesh_install/nlopt/include --with-nlopt-lib=/home/dknez/software/libmesh_install/nlopt/lib --with-capnproto=/home/dknez/software/libmesh_install/capnp --disable-parmetis --disable-ifem --prefix=/home/dknez/software/libmesh_install/opt_real/libmesh --with-methods=opt --enable-shared
```

I'll send you the xdr file via email.

**Comment by roystgnr** [comment]
Thanks!  Trying out your settings (the relevant ones at least; e.g. I don't have capnproto installed) now.

**Comment by roystgnr** [comment]
How many processors are you running on?  I'm getting a failure now, albeit not the exact same one.

Since this seems very configuration-specific, my inclination is to work on the fix and not revert #1428 unless that fix takes longer than expected, but that's a very slim inclination; if you or @jwpeterson or even some user I've never talked to before disagrees, then we can revert now and reapply a fixed version later.

**Comment by dknez** [comment]
I'm running one 1 processor.

I'm OK to wait on a fix. I can just revert my libMesh version if needed.

**Comment by roystgnr** [comment]
Switching from 4-byte to 8-byte unique_id seems to be a sufficient workaround for me; could you verify that the same is true for you?

Was your XDR file written with 64 elements somehow?  Our introduction_ex4/run.sh only does a 20-element mesh in 1D, 225- in 2D, and 216- in 3D...

**Comment by dknez** [comment]
I ran "./example-dbg -n 4 -d 3", so I wasn't using the default run.sh options.

I'll try 8-byte unique_id and let you know what happens.

**Comment by dknez** [comment]
Changing to --with-unique-id-bytes=8 fixes it for me. Should I use that from now on?

I can't remember why I'm using unique-ids, or why I used 4 bytes, so it's fine with me to switch to 8 bytes if that is recommended.

**Comment by dknez** [comment]
IIRC unique_id enables us to handle "slit meshes", is that right? In that case I do need to use that.

**Comment by roystgnr** [comment]
> Changing to --with-unique-id-bytes=8 fixes it for me. Should I use that from now on?

Apparently not, if you're the only one testing the 4 byte unique_id configuration!  I'd have been much more embarrassed if someone caught this in a release libMesh rather than in the git head, and at the moment my buildbot server (which usually tests weirder configurations than Civet) is down...

Although, I actually would suggest 8 if you're planning to do any large transient AMR on ParallelMesh.  ParallelMesh has each processor increment its own id assignments by n_procs so that they can be done without communication, and transient AMR means you're constantly destroying and creating new Dof objects, and we never renumber or even reuse-discarded unique_ids the way we do plain ids, so the numbers can get much larger much faster.

You do need unique_id (of whatever size) if you want to do restarts on any meshes where geometry exactly overlaps, that's right.

**Comment by roystgnr** [comment]
This appears to be a write() bug that will hit *anyone* who doesn't have at least one 8-byte type in play.  That's too nasty to leave in the history IMHO so I'm going to revert that PR and try again with the correct code fixup'ed in.

**Comment by roystgnr** [comment]
Ah, shoot, I can't rewrite history just by hitting the "revert" button on Github?  That just makes a new "revert" PR?

Well, I'm terrified to rewrite history on master manually, so I'll just PR the fix now...
