### ISSUE TITLE
change type of "current frequency"

### ISSUE THREAD

**Issue by BalticPinguin** [libMesh/libmesh#1465]
Dear all,
in libmesh there is a parameter called 
`equation_systems.parameters.get<Real>("current frequency")`
which is used in `src/fe/fe_compute_data.C` and `src/systems/frequency_system.C`.
I think, its only purpose is the oscillation of the infinite elements.  Am I right with this or do people use the FrequencySystem for some non-related purposes (i.e. not Helmholtz-like problem)?

So what I would like to have is that the "current frequency" is rather a 'Number', thus the oscillatory behaviour can become an exp. damping (or damped oscillation).
At least in quantum mechanics, this makes sense.
My suggestion would be to either

- change the type from Real to Number or
- add a second parameter \<Number\>("current frequency") and use this if it is set and  \<Real\>("current frequency") in other cases.

Probably the latter is advantageous since existing code doesn't need to be changed, but this leads to a bit more ugly code.
Does someone have any other/better idea, or would you rather like not to touch this at all?
Best,
Hubert

**Comment by jwpeterson** [comment]
The first option sounds OK to me, and isn't it kind of backwards-compatible in a way? Anyone using a real-valued "current frequency" before will still be able to do so after it's changed to `Number`... possibly with some trivial code changes.

I don't think many (or any?) other people currently use the infinite elements, so I'm much more willing to change APIs in those parts of the library than others...

**Comment by roystgnr** [comment]
Definitely with some trivial user code changes required; there's no mechanism by which Parameter<Real> can be converted to Parameter<Number> or vice-versa, and there's no mechanism with which Parameters can hold two Parameter objects of the same name.

My inclination with regards to infinite elements stuff is indeed "Hubert does whatever he wants here, because this is the most love that our infinite elements code has seen in years".  However, this isn't infinite elements code; IIRC we've actually had a couple other FrequencySystem users in recent years, even though none of our flagship apps or frameworks touch it.

The "proper" way to handle this upgrade IMHO would be to have the FrequencySystem code check for ```parameters.have_parameter<Number>("current frequency")```, and use it if that returns true, or use the Real type and report ```libmesh_deprecated()``` otherwise.

However... if we just keep the "current frequency" name but change the type, then old user code (with RTTI enabled, but that should be a guarantee at this point) will get a runtime error with a clear easy fix, not a wrong answer.  I wouldn't scream too loudly if I'm outvoted about that.  ... plus, it looks like much current user code may be going through FrequencySystem::set_frequencies() rather than futzing with the Parameter directly?  If that's the case then they'd still be API compatible.

**Comment by BalticPinguin** [comment]
> there's no mechanism by which Parameter can be converted to Parameter or vice-versa, and there's no  mechanism with which Parameters can hold two Parameter objects of the same name.

Ok, I wasn't aware of this, but probably your suggestion with the check for \<Number\>-type and else an `libmesh_deprecated()` report sounds good to me.
I actually feared that (especially due to the use in FrequencySystem) a type-change would be not appreciated, but seemingly not.
Ok, than I will prepare a respective PR .

**Comment by BalticPinguin** [comment]
ok, thanks.
I close this issue than.
