### ISSUE TITLE
Add function to ExodusII_IO to read additional variables from exodus

### ISSUE THREAD

**Issue by vincentlaboure** [libMesh/libmesh#1531]
Rather than going the route described by #1439 whose resolution is still an open debate, we are interested - in the meantime - in saving additional information (e.g. material ID) directly in the exodus mesh and read it during mesh construction. Our app will construct a mapping from the `top_parent()->unique_id` of each element to a structure containing the corresponding value(s).

What we need to add to libMesh is a utility function in `exodusII_io.C` that, given a variable name `elemental_var_name` and a timestep, will construct a map from the `unique_id` to the value `elemental_var_name` takes on in that element.

Merge request to come.

@YaqiWang @jwpeterson

**Comment by YaqiWang** [comment]
To make sure: `unique_id` will be set when element is created and will remain constant during the element lifetime, right?

**Comment by dknez** [comment]
This is of interest to me in the context of mesh stitching. I currently store material properties via element variables in exo files, and read those exo in and stitch them using ReplicatedMesh::stitch_meshes. However, the element variables are lost in that process, and I have to subsequently use a MeshFunction to copy the element variables to the stitched mesh. It would be better to retain the element variables during the mesh stitching somehow. Do you see that as being possible based on what you propose here?

**Comment by vincentlaboure** [comment]
@YaqiWang My understanding is that it is the case. John showed me that `unique_id`s are constructed using `set_next_unique_id` which relies on `_next_unique_id`. The latter is incremented in `replicated_mesh.C` and `distributed_mesh.C`

@dknez I can't say for sure as I have never stitched meshes together but I would think that as long as each unique_id belongs to at most one mesh, you should be in good shape

**Comment by YaqiWang** [comment]
After discussion with @vincentlaboure, we decided that currently we only need a simple wrapper in `ExodusII_IO` for `ExodusII_IO_helper::read_elemental_var_values()` because `ExodusII_IO::copy_elemental_solution()` requires `System`. We will handle the reading and broadcasting on our own and make sure the function is called before any renumbering happens.

I think the long term fix is to create a function, which returns a map from unique id to the variable value and is safe to be called before or after renumbering. But that will requires adding a map from exodus id to unique id in `ExodusII_IO` and its `read()` function. And also we will have to be able to obtain element pointer from a unique ID, which will be used in `ExodusII_IO::copy_elemental_solution()`. So my understanding is that this will not be useful to @dknez .

**Comment by YaqiWang** [comment]
I still think the best fix is to have `Elem` hold a new member variable in type of `dof_id_type` for the raw_id associated with mesh files. Then we will not have this trouble at all.
