### ISSUE TITLE
Gather std::vector<std::vector<T>>

### ISSUE THREAD

**Issue by fdkong** [libMesh/libmesh#1716]
I want to gather the distributed graph to root, and call a serial partitioner. 

`  std::vector<std::vector<dof_id_type>> _dual_graph;`

@roystgnr, Is it possible? ` communicator.gather`?

**Comment by permcody** [comment]
Fande, this isn't an optimal data structure for communication. It's possible (quite likely) that the data won't be contiguous. Have you considered using a different data structure? This graph is square right? If so, then you can play indexing tricks to keep it in a single 1D vector. I built an adjacency graph last year (you helped me with it) in MOOSE and I just created a few methods to allow normal `i, j` indexing. 

We could certainly create a method to communicate a vector of vectors, but it'll definitely require copying information before and after the communication.

**Comment by fdkong** [comment]
`std::vector<std::vector<dof_id_type>> _dual_graph;` have been living in libmesh for more than 10 years. It should be fine with me at this point. I have figured out a better to solve my problem in the PETSc side.

**Comment by roystgnr** [comment]
> ```std::vector<std::vector<dof_id_type>> _dual_graph;``` have been living in libmesh for more than 10 years. It should be fine with me at this point.

```std::vector<std::vector<dof_id_type>> graph;``` is indexed from 0 to ```n_active_local_elem```; i.e. *not* N_elem, but rather N_elem/N_proc.  I'd presumed that, if you were planning to serialize your dual_graph, you were also going to change the indexing.  Otherwise what would you do when every processor had a different idea about what ```_dual_graph[0][0]``` was?

> I have figured out a better to solve my problem in the PETSc side.

Good to hear!  Let me know if there turns out to be any gather() overload we need to add after all.

> this isn't an optimal data structure for communication. It's possible (quite likely) that the data won't be contiguous.

Ignorant question - is it possible to use ```MPI_Type_create_struct``` for ```vector<vector>``` data?  We currently use ```MPI_Pack_size/MPI_Pack/MPI_Unpack```, which are basically just fancy ways to copy stuff into a temporary contiguous buffer.  ```MPI_Type_create_struct``` is supposed to allow DMA to the interconnect, but all the examples I've seen of it are slices of data arrays, not data arbitrarily collected from anywhere in the heap.

**Comment by permcody** [comment]
> Ignorant question - is it possible to use MPI_Type_create_struct for vector<vector> data?

I don't know either, but I'm since the internal vectors could potentially be allocated at different times (due to things push_back and other reallocation needs), the actual data could be highly fragmented. I doubt there's a simple way to get the create struct stuff to work for this case.

**Comment by friedmud** [comment]
Yeah - to make this work you will _have_ to make a copy of the data... pack
that copy, send, then unpack on the other side.
