### ISSUE TITLE
Parameter in `libMesh::EigenSparseMatrix<T>::add` should be `const`

### ISSUE THREAD

**Issue by dmcdougall** [libMesh/libmesh#1915]
The argument `X` in `void libMesh::EigenSparseMatrix<T>::add(const T a, SparseMatrix<T> & X)` ought to be `const`.

[Here's](https://libmesh.github.io/doxygen/classlibMesh_1_1EigenSparseMatrix.html#a5d2bdb0f718d4b440941f8471672aba7) the part of the documentation I am looking at.

**Comment by jwpeterson** [comment]
I agree that it should. 

I suspect we originally ended up with a non-const reference for `X` because the `PetscMatrix` override calls [MatAXPY](https://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/Mat/MatAXPY.html) which is expecting a non-const `Mat`... 

Have you tried making this change throughout the `SparseMatrix` hierarchy and seeing if anything breaks? You might need a const-cast in `PetscMatrix` to get that particular bit to work, but otherwise I think the change would be nicely backwards-compatible.
