### ISSUE TITLE
what happen in LibMeshInit init (argc, argv)?

### ISSUE THREAD

**Issue by ermore** [libMesh/libmesh#1994]
when run this test code,  I found that the answer was different from what I had imagined.
```
#include <iostream>
#include "libmesh/libmesh.h"
#include "libmesh/mesh.h"
using namespace libMesh;

int main (int argc, char ** argv)
{
  LibMeshInit init (argc, argv);
  int rank,size;
  MPI_Comm_rank(MPI_COMM_WORLD,&rank);
  MPI_Comm_size(MPI_COMM_WORLD,&size);

  std::cout<<"rank: "<<rank<<"  size is "<<size<<std::endl;

  return 0;
}
```
When I execute the following commands:mpiexec -n 3 ./example-opt
the result is: 
```
rank: 0  size is 3
```
But I think its result should be:
```
rank: 0  size is 3
rank: 1  size is 3
rank: 2  size is 3
```

**Comment by jwpeterson** [comment]
libmesh suppresses output on all nonzero ranks by default. If you want to see this output, run your code with the `--keep-cout` command line option. Note: output from different processors may be interleaved when running this way, you it may help to send each rank's output to a separate file with the `--redirect-output` flag.

**Comment by roystgnr** [comment]
The default behavior after LibMeshInit construction is to send cerr on every processor to the terminal (because you want to immediately know about something unexpected on any rank) but to disable cout on every rank except rank 0 (because you want to be able to ```std::cout << "Starting program"``` and see one copy of that rather than one hundred).

You can get different behavior with command line options ```--keep-cout``` (which makes cout print from all processors), ```--drop-cerr``` (which silences cerr on all processors), ```--redirect-output some_file_name``` (which redirects cout to some_file_name.processor.3 from processor 3, etc), and/or --separate-libmeshout (which causes our libMesh::out and libMesh::err to be independent new std::ostream objects that you can fiddle with as you please without affecting your own cout/cerr code).

**Comment by jwpeterson** [comment]
I'm going to close this since it does not seem to be an issue with the code so much as a general question, but please feel free to re-open if you have further comments.
