### ISSUE TITLE
Partitioning sometimes required for MeshRefinement

### ISSUE THREAD

**Issue by bboutkov** [libMesh/libmesh#2022]
Hi all.

Ive encountered some situations where it appears that having an attached partitioner is required in order to do some basic uniform refinement/coarsening operations using a DistributedMesh; this in turn adds a decent amount of overhead for me while preparing GMG related structures. 

You can check out a small example that triggers this behavior using ```mpiexec -np 2``` on a modified intro/ex4 at:  https://github.com/bboutkov/libmesh/tree/mandatory_partitioning

Its interesting to note that the attached example seems to run to completion ok in opt, yet in dbg it hits asserts [1], [2]. Although I can seemingly ignore these asserts, I would be grateful if someone could help me to understand the situation better in order to track down some more subtle bugs I've been chasing further down the line.  Thanks as always for any input!

 [1] https://github.com/libMesh/libmesh/blob/031f0b35b492da15428c027bf872fec0b2f43902/src/geom/elem_refinement.C#L82

and 
[2] https://github.com/libMesh/libmesh/blob/3679dac7b2836f2e63f06fb3f2bf2bb55bd39ede/src/geom/elem_refinement.C#L98

**Comment by bboutkov** [comment]
As a note, I think the part of the idea here is the placement of my calls to  ```mesh.allow_remote_element_removal(false);```

I had been using it after already doing some initial refinement to mimic my testing environment when running through GRINS. If I move this call to a location prior to the initial refinement things appear to be OK. 

Im going through the process of changing my workflow to  incorporate this new change and will run some more tests, but maybe the answer to this ticket is something like "dont change mesh refinement properties" after already refining the mesh?

Still not quite clear how the partitioner ties into this, but if I can obviate the problem altogether in this manner then its sufficiently satisfactory for my purposes. Will post updates upon retesting the new workflow.

**Comment by bboutkov** [comment]
.....and it looks like I spoke too early. While that one case was fixed, there still appears to be dof locality issues which now creep up at ```mpiexec -np 3```. Again theyre 'fixed' by the partitioner being enabled, or if I move the partitioner disabling to pre-initial-refinement. 

The problem is that if I initially disable the partioning then only the coarse mesh will be load balanced, and upon GMG refinement the balance will deteriorate when meshes have mixed elements which happen to have partitions with elements which create more children than others. Maybe this is me worrying too early about load balance, but I could envision mixed dimension mesh scenarios with for example quads on one proc and pyramids on another which would become quite lopsided after only a few refinements.

**Comment by roystgnr** [comment]
Sorry this got buried so far down my todo list.

So what's happening here:

You uniformly refine the mesh and EquationSystems::reinit.  All the standard behavior is still enabled, so this prompts us to remove remote elements when preparing the changed mesh.  We now expect to see some cases where a local element has a ghosted neighbor, and that ghosted neighbor has a ghosted parent but also (in 2D) one or two remote siblings.

You turn off the partitioner and remote element removal, and uniformly coarsen the mesh.  The mesh is still valid at this point, but there's a now-active ghosted neighbor element with some subactive children, still a mix of ghosted and remote.

You uniformly refine the mesh.  Elem::refine() apparently hasn't actually been properly tested on a DistributedMesh with subactive elements (because we don't actually use those often; they were originally intended mainly for GMG!), so it was never made remote_elem aware like Elem::coarsen had to be.

Let me try fixing that first; doing so will surely just reveal more bugs but it's at least a start.

**Comment by roystgnr** [comment]
The newly-revealed bug now is that your modified example triggers a bug in DofMap::local_variable_indices(), which assumes that node partitioning is assigned in the traditional libMesh way, even though we've had more explicit options (and as in your case, some implicit issues) for that for a while.

**Comment by roystgnr** [comment]
> some more subtle bugs I've been chasing further down the line.

Keep posting test cases for anything you hit?  I'll want to close this after #2111 and #2112 are merged, but just because I fixed the stuff uncovered here doesn't mean you're not still exploring new territory that will hit new bugs.

> Thanks as always for any input!

Does "any" include "months-delayed"?  I apologize again about that.  It's been a rough few months, but If I'd had any idea that this was going to take hours to fix instead of weeks then I'd have gotten to it right away.

**Comment by bboutkov** [comment]
Thank you for taking a look at this issue; as it wasn't the biggest problem on my plate the delay wasn't really an problem for me, so dont worry about it! These changes do look indeed look promising, I had more or less suspected the first asserts to be overzealous but wasn't sure about the right way about getting rid of them.

After these fixes get merged and I have a spare moment Ill re-enable these code paths on my end and run some more extensive studies, I'll let you know if I find anything further, but my hunch is there should be nothing immediate as I had earlier been able to obviate these issues by simply using METHOD=opt. Thanks again!
