### ISSUE TITLE
Invalid file links in 1.4 release candidate

### ISSUE THREAD

**Issue by drwells** [libMesh/libmesh#2046]
I downloaded a copy of the 1.4 release candidate earlier and noticed some odd errors:
```
tar: libmesh-1.4.0-rc1/contrib/tecplot/binary/lib/x86_64-apple-darwin12.5.0/tecio.a:
Cannot hard link to ‘libmesh-1.4.0-rc1/contrib/tecplot/binary/lib/x86_64-apple-darwin13.1.0/tecio.a’:
Invalid cross-device link
tar: Exiting with failure status due to previous errors
```

This only occurs for some of the `tecio.a` archives: I see tar errors for (Darwin) 10.8.0, 12.2.0, 11.4.2, 12.2.1, 10.7.0, and 12.5.0 and x86_64-pc-linux-gnu. I believe the rest are fine (i.e., I found 16 archives but expected 23).

For the record: I am using AFS.

**Comment by jwpeterson** [comment]
Thanks for this report! I will try and look into this and fix it before the next RC... Do you get this for all three of the file formats (gz, bz2, xz)? Do you get the same thing for the [tarball provided by GitHub](https://github.com/libMesh/libmesh/archive/v1.4.0-rc1.tar.gz)?

**Comment by drwells** [comment]
I went back and checked all of the links:
1. https://github.com/libMesh/libmesh/archive/v1.4.0-rc1.tar.gz works
2. https://github.com/libMesh/libmesh/releases/download/v1.4.0-rc1/libmesh-1.4.0-rc1.tar.xz has errors
3. https://github.com/libMesh/libmesh/releases/download/v1.4.0-rc1/libmesh-1.4.0-rc1.tar.gz has errors
4. https://github.com/libMesh/libmesh/releases/download/v1.4.0-rc1/libmesh-1.4.0-rc1.tar.bz2 has errors

Its not clear to me what makes the assets different from the release but those three all have the same problem with static archives.

**Comment by jwpeterson** [comment]
Number 1 is a tarball generated by GitHub itself, numbers 2-4 we generate ourselves by running "make dist" and upload to the release manually. So it at least makes sense that all the broken ones came from the same source... also since you had the same problem with each I'm fairly certain the issue is with the underlying tar format and not the compression applied on top of it.

I have definitely seen problems in the past with tarballs generated by running "make dist" on OSX, so we always generate them on a Linux box now. I haven't seen a case where a Mac has trouble opening a tarball created under Linux. I also don't have a Mac handy at the moment for testing (and all of these untar for me just fine under Ubuntu) so I might need your help in tracking down the problem...

**Comment by drwells** [comment]
I can only reproduce this issue on my workstation; its likely due to something strange AFS is doing.

**Comment by jwpeterson** [comment]
OK, well it's good there is the one working tarball from GitHub I guess... if I come across anything relevant I'll try and post on this issue. If anyone else out there on a Mac using AFS or not (maybe @milljm has a second to try this) wants to try unpacking one of these tarballs, that would also be awesome!

**Comment by drwells** [comment]
I think we may be talking about two different things: the AFS I am using is the distributed Linux file system, not the new Mac one.

**Comment by jwpeterson** [comment]
Ha, indeed we were... the apple one is APFS.

**Comment by milljm** [comment]
The files listed as having errors, extracts okay for me on Mojave with APSF.
But I see you guys have already figured that out...

John knows I have plenty of systems at my disposal. I wouldn't mind doing some testing.

**Comment by jwpeterson** [comment]
Thanks @milljm!

If we are to believe this [old forum post](https://www.pgroup.com/userforum/viewtopic.php?p=1206), it's possible that "The AFS filesystem doesn't do hard links between directories." That would explain why the tarball from GitHub works on your system, as it contains only symbolic links (which AFS does support) while the "make dist" tarballs turn all those symbolic links into hard links for some reason. I'm not sure whether it's possible to control this behavior within the automake build system.

**Comment by drwells** [comment]
Yup, thats definitely it: all the missing archives are hard-linked across directories.

**Comment by jwpeterson** [comment]
FYI, I believe I've tracked this issue down to the command that "make dist" runs to create the tarballs, i.e. 
```
tardir=libmesh-1.4.0-pre && tar --format=ustar -chf - "$tardir" | XZ_OPT=${XZ_OPT--e} xz -c >libmesh-1.4.0-pre.tar.xz
```
In particular, the `-h` flag they use, which does the following:
```
-h, --dereference
       Follow symlinks; archive and dump the files they point to.
```
I don't know exactly what they mean by "dump" but apparently it results in making a hard link in the tar archive. I can kind of see why they would use this option by default, so that you wouldn't accidentally make a tarball with a broken/dangling symbolic link to something outside the main repo, but I don't think we really need it for libmesh. If it's possible to control the tar options used by autoconf, I'd definitely consider removing the `-h`...

**Comment by jwpeterson** [comment]
@drwells would you mind giving the RC2 release tarballs a try? They should not contain any hard links, so hopefully they will work on AFS now. Thanks.

**Comment by drwells** [comment]
It works: thanks a lot!

**Comment by jwpeterson** [comment]
OK, good to know. The tarballs got about 10% bigger due to this change, but I think the extra portability is worth it.
