### ISSUE TITLE
Detect dof-id-bytes

### ISSUE THREAD

**Issue by friedmud** [libMesh/libmesh#2060]
Right now libMesh will thrown an error if I compile PETSc with 64bit indices and try to use `--with-dof-id-bytes=4` (or vice versa).

It would be great if we didn't need to specify "dof-id-bytes" at all... and just have it be autodetected to use the same thing PETSc is using.

**Comment by roystgnr** [comment]
Agreed.  We don't get an error until runtime, do we?

Autodetection might be a bit tricky, because I'd want to differentiate between a lack of --with-dof-id-bytes settings (in which case we'd want to autodetect) and an explicit incompatible --with-dof-id-bytes setting (in which case we'd want to scream and die rather than silently override it and continue).

But screaming and dying at configure time rather than wasting a bunch of build time ought to be easy at least.

**Comment by jwpeterson** [comment]
> We don't get an error until runtime, do we?

It's a configure time error.

**Comment by roystgnr** [comment]
Huh, I actually thought I remembered you making that change, then a quick GitHub search and m4 grep couldn't find anything.  Where are we testing compatibility?

**Comment by jwpeterson** [comment]
Same thing for real/complex scalar mismatch:

https://github.com/libMesh/libmesh/blob/3b7027afa0b09774e368ca47aa55a2a3b88189ef/m4/libmesh_optional_packages.m4#L162-L189

I haven't tested what happens if we were to just change the value of `$dof_bytes` to be consistent at this point in the code instead of throwing an `AC_MSG_ERROR`, but it seems like it could work.

**Comment by roystgnr** [comment]
Ah, I was grepping for dof_id_bytes.

**Comment by jwpeterson** [comment]
Yeah, in `AC_ARG_WITH`, you can detect defaults/when the user does not use the flag.
```
AC_ARG_WITH([dof_id_bytes],
            AS_HELP_STRING([--with-dof-id-bytes=<1|2|4|8>],
                           [bytes used per dof object id, dof index [4]]),
            [dof_bytes="$withval"],
            [dof_bytes=4])
```
So we could have an extra variable, `$dof_bytes_is_default` that defaults to "yes" but gets set to "no" in the second case above.
