### ISSUE TITLE
Feature Request: 3D mesh with 1D elements in GMSH mesh files (.msh)

### ISSUE THREAD

**Issue by SpaceSapien** [libMesh/libmesh#2133]
I wanted to ask if a 3D mesh with 1D elements would be able to be added for GMSH .msh files.

See
https://groups.google.com/forum/#!topic/moose-users/zRud9vjgvzM

Thanks

**Comment by jwpeterson** [comment]
If I recall correctly, there was no gmsh-official way to determine whether lower-dimensional elements are present in the mesh file because a) they represent lower-dimensional elements which should be present in the mesh, or b) they are only being used to represent boundary conditions. 

The approach which Martin Lesueur came up with to handle this was to add the "lower_dimensional_block" string to the PhysicalNames section to indicate that a given element set should be maintained in the final mesh as lower-dimensional elements. So, for example, the PhysicalNames section might look something like the following:
```
2 1 "frac" lower_dimensional_block
2 3 "top"
2 4 "bottom"
3 2 "volume"
```
And then we would know to keep the elements of the "frac" block around for use later. I don't see any reason why this approach wouldn't work for meshes with 1, 2, and 3 dimensional elements present. In fact, it may just "work" if you take out this check that's currently in the code: 
```c++
// Have not yet tested a case where 1, 2, and 3D elements are all in the same Mesh,
// though it should theoretically be possible to handle.
if (n_dims_seen == 3)
  libmesh_error_msg("Reading meshes with 1, 2, and 3D elements not currently supported.")
```
and of course mark all the lower_dimensional_blocks appropriately. I don't have time to try this out myself, but it should be pretty easy to at least get to the next relevant error message and then maybe somebody can pick it up from there.

Note that the test.gmsh file that you linked on the MOOSE mailing list is not a mesh file but a gmsh input file. I have not used this lower_dimensional_block feature before myself so I think it may have to be appended manually once the actual mesh file is generated, as it is a libmesh-specific feature.

**Comment by lindsayad** [comment]
@SpaceSapien I know that this issue came out of the moose users list. For what it's worth, if you have created physical groups in your gmsh input (whether using the old scripting `.geo` files or using gmsh's new cool python/C/C++ APIs) corresponding to boundaries, you can use MOOSE mesh modifiers to generate lower dimensional element blocks from those "boundaries". See [here](https://github.com/idaholab/moose/blob/next/framework/src/meshmodifiers/LowerDBlockFromSideset.C). However,

> I have not used this lower_dimensional_block feature before myself so I think it may have to be appended manually once the actual mesh file is generated, as it is a libmesh-specific feature.

I ***have*** verified that this feature works, and you can/should do it in your gmsh input file, e.g. with 
`Physical Line ("blah_blah_blah_lower_dimensional_block")`

**Comment by SpaceSapien** [comment]
Thanks everyone,

The changes you suggested worked, and now I understand how to use the _lower_dimensional_block. I did not check to see if it worked with the newer gmsh format, but it works for 


https://github.com/libMesh/libmesh/pull/2139
#2139

**Comment by SpaceSapien** [comment]
Now fixed in master .
