### ISSUE TITLE
Add zlib m4

### ISSUE THREAD

**Issue by lindsayad** [libMesh/libmesh#2135]
We need to be able to specify a non-default path for libz.

It looks like there is already a canonical m4 file for libz, so I will just use that.

But @jwpeterson how the ^*@$ do I make the added m4 show up in bootstrapped files? Do I need to add something to configure.ac?

**Comment by jwpeterson** [comment]
I don't think so, it will show up in aclocal.m4 (autogenerated by configure I believe), but only if you actually call one of the functions in it.

**Comment by jwpeterson** [comment]
Is this coming up in new versions of Ubuntu? Or some weirder OS?

If you are still having trouble, just push your branch that you have so far and I can take a look later tonight.

**Comment by lindsayad** [comment]
The problem is that @YaqiWang is using a Qt provided by conda in Rattlesnake which has various dependencies that bleed down into a conda libpng using a conda provided libz. However, libmesh detects and uses the system libz. So if we link his isoxml binary with libmesh libraries, then at run-time we get a complaint out of `libpng` that it can't find the right version of `libz`.

**Comment by jwpeterson** [comment]
:open_mouth:

**Comment by lindsayad** [comment]
I guess maybe a first question is why libMesh is linking in libz at all...?

**Comment by lindsayad** [comment]
Hmm, well it looks like for me PETSc it linking in libz 😦

**Comment by lindsayad** [comment]
Yea this is a library dependency being brought in through PETSc (through PTScotch), so being able to specify a differerent zlib dir on the libmesh end would not help (and only hurt). so I'm going to close this.

**Comment by YaqiWang** [comment]
Good to know. Thanks @lindsayad !

**Comment by jwpeterson** [comment]
> I guess maybe a first question is why libMesh is linking in libz at all...?

We have contrib/gzstream that allows one to directly write gzip-compressed files using the C++ streams interfaces, and that requires libz. It's enabled by default but it can be configured off with `--disable-gzstreams` if desired.

After a closer look, however, it appears that only some of the older I/O classes actually use gzstream, and `NameBasedIO` just uses system calls to uncompress files before reading them, so we could probably do the same thing on the writing end if it was really desired. So I think we could probably get rid of it entirely, but it sounds like you found the problem was somewhere else anyway...
