### ISSUE TITLE
libmesh-config --ldflags returns empty string

### ISSUE THREAD

**Issue by milljm** [libMesh/libmesh#2177]
I can see ldflags being populated in the libmesh_config.h file, but for some reason asking libmesh-config for those flags returns nothing:

```
[ ]> cat $LIBMESH_DIR/include/libmesh/libmesh_config.h | grep -i ldflags
#define LIBMESH_CONFIGURE_INFO "./configure  '--prefix=/usr/local/Cellar/moose-libmesh/f3dd9fe' '--with-methods=opt' '--enable-silent-rules' '--enable-unique-id' '--disable-warnings' '--with-thread-model=openmp' '--disable-maintainer-mode' '--enable-petsc-hypre-required' '--enable-metaphysicl-required' 'CXX=mpicxx' 'LDFLAGS=-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib' 'CPPFLAGS=-I/usr/local/opt/llvm/include' 'CC=mpicc' 'FC=mpif90' 'F77=mpif77' 'PETSC_DIR=/usr/local/opt/moose-petsc'"
```

```bash
[ ]> METHODS=opt $LIBMESH_DIR/bin/libmesh-config --ldflags

[ ]>
```

Is there another way to return the same ldflags used to build libMesh? This _might_ be related to #1544

**Comment by jwpeterson** [comment]
In `contrib/bin/libmesh-config.in`, it looks to me that `libmesh-config --ldflags` returns the value of the `libmesh_LDFLAGS` variable variable that was set during configure, and not the plain old `LDFLAGS` variable. This is related to the same issue we have with `libmesh_CXXFLAGS` (#2164), and is due to a historical decision that we made where we didn't want to trust the environmental values of `CXXFLAGS` and `LDFLAGS` as these were sometimes set incorrectly for building libmesh on certain clusters... I don't believe this is currently an issue any longer, so we could possibly do away with the concept of using `libmesh_CXXFLAGS/LDFLAGS` all together.

A quick fix in your case might be to set the `libmesh_LDFLAGS` environment variable on the configure line, possibly in addition to setting `LDFLAGS` for the moment.

**Comment by milljm** [comment]
That should work for what I am doing (Homebrew). I'll give that a try and report. Thanks!

**Comment by milljm** [comment]
Thank you, that worked:

```bash
[ ]> METHODS=opt /usr/local/opt/moose-libmesh/bin/libmesh-config --ldflags
-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib
```
