### ISSUE TITLE
How to store the matrix and reuse for different equations?

### ISSUE THREAD

**Issue by Laphet** [libMesh/libmesh#2263]
Hi, it is me again!

I encounter a situation: I have three equations to solve, those equations share the same linear operator (matrix) while the RHSs are different. 

I wonder whether there is a neat way just like PETSc--- define an operator first and solve separately.  To my understanding, I need to define three "System", add three variables, attach three assemble functions (they almost do the same thing!),...

Thanks!

**Comment by roystgnr** [comment]
No, you can do this with a single System; just put a switch in your assemble function that chooses which RHS to assemble based which solve you're currently working on.  That's step 1: correctness.  Assuming you want to hang on to all three solutions at once, you'll either clone the solution vector yourself or add_vector() to create more storage space attached to the System, then you can swap() your solution with those vectors (and do System::update() as necessary to keep the ghosted current_local_solution in sync).

Step 2 is efficiency.  First, turn off ImplicitSystem::zero_out_matrix_and_rhs and manage that yourself: you'll want to zero out the rhs on solves other than your initial solve, but you'll keep track of whether you've built the matrix already and you'll just leave it built if so.  Second, you'll set LinearSolver::reuse_preconditioner after your first solve so that later solves don't have to recompute that either.

**Comment by jwpeterson** [comment]
Closing because I think this isn't actually an issue per se and the conversation seems to have ended.
