### ISSUE TITLE
fem_system_ex1 fails with PETSc 3.12

### ISSUE THREAD

**Issue by jwpeterson** [libMesh/libmesh#2295]
I don't think we are testing libmesh PRs with PETSc 3.12 yet (?) but I have it built locally and I currently get the error below from the fem_system_ex1 invocation with command line args set to "insanity level 5":
```
./example-dbg solver_type=petscdiff coarsegridsize=6 coarserefinements=2 transient=false n_timesteps=1 --use_petsc_dm --node-major-dofs -snes_view -snes_monitor -snes_converged_reason -snes_rtol 1.0e-4 -ksp_type fgmres -ksp_rtol 1.0e-5 -pc_type fieldsplit -pc_fieldsplit_0_fields 0,1 -pc_fieldsplit_1_fields 2 -pc_fieldsplit_type schur -pc_fieldsplit_schur_fact_type full -pc_fieldsplit_schur_precondition a11 -fieldsplit_0_pc_type mg -fieldsplit_0_pc_mg_galerkin both -fieldsplit_0_pc_mg_type full -pc_mg_levels 3 -fieldsplit_0_pc_mg_levels 3 -fieldsplit_0_mg_levels_pc_type sor -fieldsplit_0_mg_levels_pc_sor_its 5 -fieldsplit_0_mg_levels_ksp_type richardson -fieldsplit_0_mg_levels_ksp_richardson_self_scale -fieldsplit_0_mg_levels_ksp_max_it 5 -fieldsplit_0_mg_coarse_pc_type lu -fieldsplit_0_mg_coarse_ksp_type preonly -fieldsplit_0_ksp_max_it 1 -fieldsplit_0_ksp_type gmres -fieldsplit_p_ksp_max_it 5 -fieldsplit_p_ksp_type gmres -fieldsplit_p_pc_type none -fieldsplit_p_ksp_rtol 1.0e-4 -fieldsplit_p_inner_pc_type lu -fieldsplit_p_inner_ksp_type preonly -fieldsplit_p_upper_pc_type lu -fieldsplit_p_upper_ksp_type preonly
```

```
[0]PETSC ERROR: --------------------- Error Message --------------------------------------------------------------
[0]PETSC ERROR: No support for this operation for this object type
[0]PETSC ERROR: DM type shell does not implement DMCreateInterpolation
[0]PETSC ERROR: See https://www.mcs.anl.gov/petsc/documentation/faq.html for trouble shooting.
[0]PETSC ERROR: Petsc Release Version 3.12.0, Sep, 29, 2019 
```
I'm guessing maybe it's something to do with 3.12 because that seems to be the version where things got moved out of the `dm->ops` to a more public API, but beyond that I'm not sure what the issue might be.

@bboutkov

**Comment by bboutkov** [comment]
> with command line args set to "insanity level 5": 

Hahaha. Unfortunately, it can get even worse for this example if you start touching the inner and upper solves. Using GMG for more complicated multiphysics problems only exacerbates the insanity... I think the right way to set these settings is in a more block-structured and visual manner where you can somehow see what settings touch which block, but this isn't as easy to achieve as I would like for the moment.

Anyways, I think I can reproduce this error and it looks like a minor bug on my end. Since you mention that we don't have CI coverage for PETSc version 3.12.0 yet maybe you would like to give my bug fix branch [1] a test and if it works as expected I'll go ahead and create a PR to address this issue. 

[1] : https://github.com/bboutkov/libmesh/tree/fix_subdm_func_propagation

**Comment by jwpeterson** [comment]
Thanks @bboutkov, this fixes the issue for me. I'll open a PR for your branch.
