### ISSUE TITLE
compilation error without "--enable-unique-id"

### ISSUE THREAD

**Issue by bzjan** [libMesh/libmesh#2309]
First time user here. I am trying to compile libMesh on Ubuntu 18.04 with the following commands:

```
cd ~/source
git clone git://github.com/libMesh/libmesh.git 
cd libmesh
git submodule update --init
mkdir build
cd !$
../configure METHODS="opt" --disable-fortran --enable-unique-id
make
```

This works. However, without "--enable-unique-id", I get the following error:

```
 CXX      src/mesh/libmesh_opt_la-unstructured_mesh.lo
../src/mesh/unstructured_mesh.C: In member function ‘virtual void libMesh::UnstructuredMesh::copy_nodes_and_elements(const libMesh::UnstructuredMesh&, bool, libMesh::dof_id_type, libMesh::dof_id_type, libMesh::unique_id_type)’:
../src/mesh/unstructured_mesh.C:116:9: error: ‘newn’ was not declared in this scope
         newn->add_extra_integers(n_new_node_ints);
         ^~~~
../src/mesh/unstructured_mesh.C:116:9: note: suggested alternative: ‘nan’
         newn->add_extra_integers(n_new_node_ints);
         ^~~~
         nan
../src/mesh/unstructured_mesh.C: In member function ‘void libMesh::UnstructuredMesh::create_submesh(libMesh::UnstructuredMesh&, const libMesh::MeshBase::const_element_iterator&, const libMesh::MeshBase::const_element_iterator&) const’:
../src/mesh/unstructured_mesh.C:773:9: error: ‘newn’ was not declared in this scope
         newn->add_extra_integers(n_node_ints);
         ^~~~
../src/mesh/unstructured_mesh.C:773:9: note: suggested alternative: ‘nan’
         newn->add_extra_integers(n_node_ints);
         ^~~~
         nan
```

A look at the code section in unstructured_mesh.C for the first error shows:

```
        // Add new nodes in old node Point locations
#ifdef LIBMESH_ENABLE_UNIQUE_ID
        Node * newn =
#endif
          this->add_point(*oldn,
                          oldn->id() + node_id_offset,
                          added_pid);

        newn->add_extra_integers(n_new_node_ints);
        for (unsigned int i = 0; i != n_old_node_ints; ++i)
          newn->set_extra_integer(extra_int_maps.second[i],
                                  oldn->get_extra_integer(i));
```
Questions:

1. Does that mean that `newn` is not declared, when the program is not compiled with "--enable-unique-id"?
2. Should I just always add that compiler flag or are there reasons to leave it out (performance,...)?

The working and failing config logs are attached.

[bad_config.log](https://github.com/libMesh/libmesh/files/3775259/bad_config.log)
[good_config.log](https://github.com/libMesh/libmesh/files/3775260/good_config.log)

**Comment by roystgnr** [comment]
Gah, this looks like a bug I introduced last Friday in #2304.  All our power users (and more importantly on this timescale, apparently all our CI tests?) enable unique_id(), so you're the first to catch it.  I'll have a fix in master shortly; thanks so much for the report!

To answer your questions:

1. Yes - previously that pointer was only used for a unique_id setting elsewhere in the code, so we had it wrapped to avoid "unused variable" warnings when unique_id was disabled.
2. Currently enabling unique_id() costs a little CPU time, but more significantly it costs 8 bytes per DofObject (Node or Elem).

For a first-time user, you might want to try the libMesh 1.5.0 release rather than the git master.  There's no guaranteed-bug-free version I'm afraid, not with every system and build configuration possible, but with a release version you're getting a branch from a well-tested point in git history, with backported bugfixes only after that point; with git master you're getting all the bleeding-edge feature additions too, including the complicated refactorings and the rushed features that recently prompted us to fork off a pre-modification stable release in the first place!
