### ISSUE TITLE
Optimize periodic boundaries ?

### ISSUE THREAD

**Issue by lindsayad** [libMesh/libmesh#2369]
We have a user on our [mailing list](https://groups.google.com/forum/#!topic/moose-users/7ZwXz6Ztlrc) who is spending a lot of time in his simulation finding periodic boundary neighbors as shown by this profile that I generated for him:

![periodic-boundaries-profile](https://user-images.githubusercontent.com/10248304/70651622-035c8d00-1c06-11ea-9fef-4a25014eda76.png)

You can see that we have a diamond pattern where we branch in `EquationSystems::reinit_solutions` to `System::reinit_constraints` and `DofMap::distribute_dofs` and then end up calling `PeriodicBoundaries::neighbor` from both of those branches. Is there a way we could cache information so that one of these branches just uses the information generated by the other?

Also perhaps this deserves its own issue...but should we make the effort to detect when we're running with only one process and then skip adding algebraic ghosting? I ran this profile serially so in an ideal world I feel like I shouldn't see the second branch happening at all. (The stack from DofMap::distribute_dofs down to PeriodicBoundaries::neighbor runs through DofMap::merge_ghost_functor_outputs)

**Comment by roystgnr** [comment]
Ghosting is just one of a few things we should be skipping in serial but aren't, IIRC.  I'll take a look at that first since it should be an easier and more obvious fix.

With those periodic neighbors, I think my first big question is: why exactly are we falling back so heavily on a linear search?!  Of course hunting across the domain is going to be slow if it's O(N) rather than O(log N).

At first glance - I see an interface added in #1012 that **only** does a linear search?  We're not actually using that now, are we?

**Comment by jwpeterson** [comment]
I did have [concerns](https://github.com/libMesh/libmesh/pull/1012#issuecomment-229767034) about this linear search at the time. Apparently performance was not an issue for @snschune's application at the time, but now it seems like it is? Without looking at it in too much detail, would it be possible in this application to not call the version of `PointLocatorTree::operator()` that triggers this linear search?

**Comment by roystgnr** [comment]
We are actually using that now.  When the linear search implementation was added for the candidate_elements search, I didn't worry about it because surely none of *my* code was going to use it.  Then when we had issues with PeriodicBoundaries and overlapping elements, I must have seen that the candidate_elements API and it was an obvious fix, but forgotten that the current implementation was too slow to be usable.

Let me see how hard this is going to be to fix properly.

**Comment by jwpeterson** [comment]
I think this issue has been addressed but @roystgnr or @lindsayad should feel free to re-open if I'm wrong.

**Comment by roystgnr** [comment]
IMHO #2377 counts as a fix for this, yeah.  I'll consider myself corrected if someone manages to come up with a case that profiles otherwise, though.
