### ISSUE TITLE
Infinite elements get wrong properties

### ISSUE THREAD

**Issue by BalticPinguin** [libMesh/libmesh#2432]
I finally digged into another issue with infinite elements: My problem always was that ``weight``, ``dweight`` and ``dphase`` seemingly a bit off: ``dphase``, e.g., should correspond to ``r/r.norm()`` wherere ``r`` is the vector from the origin() to the physical point.

According to my analysis now, the issue seems not in these quantities but that the quadrature points ``xyz`` are wrong: While the above-mentioned quantities are computed from the ``InfFE``-object, ``xyz`` and the jacobian are computed in the respective ``FEMap``-object. There, however, the quantities are computed via Lagrange interpolation. But in case of infinite elements, the functions are NOT of Lagrange-type.

One straight-forward way to fix this would be to use the function [combine_base_radial](http://libmesh.github.io/doxygen/classlibMesh_1_1InfFE.html#a07964b091022a4b60b205053fe2fc8c0) where we anyway compute some ``FEMap``-quantities outside of the ``FEMap``-class, so one might just add the ``xyz``-values at this place.

But it is a quite hacky solution, so (reference to #1149)  one might discuss some (hopefully not too difficult) reordering to straighten the logic here?

Just for the protocol: [here](https://gist.github.com/BalticPinguin/56d5ee3fd9f81f560dd0947ae35ec22a) is a gist with the extended test for infinite elements where one can check the erroneous behaviour.

**Comment by BalticPinguin** [comment]
>One straight-forward way to fix this would be to use the function combine_base_radial where we anyway compute some FEMap-quantities outside of the FEMap-class, so one might just add the xyz-values at this place.

This was a bit too fast: seemingly, the scheme with ``InfFE`` and ``FEMap`` works well enough that there is no place where all needed quantities are available; so one might need some restructuring:
   * one could create some dummy ``phi_map`` using Lagrange-type infinite elements; if one corrects for the global ``1/r``-factor, the normal scheme (inside ``FEMap``) should work.
   * one can, as I thought yesterday, extend the ``InfFE``-class to get the full transformation properties and compute the quadrature points in physical space there.

Even though I'd like to fix it ASAP and without spending too much work, I would find it much more convincing to try to restore the separation of tasks to the two classes....

Any ideas, comments?

**Comment by roystgnr** [comment]
I'd be happy to just follow your lead on this one, I'm afraid to admit, but a few thoughts anyway:

By the idea of a "dummy phi_map", you mean something such that sum(node_i phi_i(qp)) would indeed give the physical space location of the quadrature point at qp in master space?  That sounds ideal, but I don't see how it's possible in general, since the radial order can be arbitrarily high but you only have one radial layer of nodes to work with; once order>1 doesn't that mean you no longer have a one-to-one correspondence between nodes and mapping shape functions?

**Comment by BalticPinguin** [comment]
... I think the idea with ''dummy phi_map'' has two problems: First, one has than two ``phi_map``s and the second is that the ``dummy``-variant would need to have more radial nodes (i.e. the Lagrange-nodes) to work. So this might be not the best way.

Currently, I started to implement a scheme using ``InfFE::map()`` to compute the correct points.
My idea is to also change the structure a bit, hoping to make it easier to follow: e.g. currently the ``InfFE::combine_base_radial()``, ``InfFE::init_shape_functions()`` and ``InfFE::compute_shape_functions()`` compute some of the quantities but not exactly what I would expect from the name: `` combine_base_radial`` computes ``phi`` and ``phi_map`` in reference space (what usually is done by ``FEMap``, ``compute_shape_functions`` computes ``dphase`` and ``dweight`` but ``weight`` is computed within ``init_shape_functions()``.

My goal is to shift parts of these calculations to ``FEMap`` which than needs some further functions/interfaces when infinite elements are enabled.
But than the general workflow is more similar for ``FE`` and ``InfFE``.

In a ``FIXME`` (in ``inf_fe.h``), @pbauman suggested
> A proper implementation would subclass this class and hide all the radial function business.

However, I would refrain from an ``InfFEMap`` to not get into the same problem as with ``FE`` and ``InfFE``?

**Comment by BalticPinguin** [comment]
after a long time, I finally can report progress with this issue: Unfortunately, there is some quite bad news with it: By correcting the computation of the quantities, I almost completely broke the APIs and the nice resemblance of ``FE`` and ``InfFE`` is gone. I'll give more details when doing the PR (the most important and, when thinking about it rather obvious, issue is that the jacobian diverges, since it maps to an element with infinite volume).

But I have another question: similar to the Jacobian, also the ``phi_map`` and ``dphd{xi,eta,zeta}_map`` and respective ``psi``-quantities diverge.
If I see it correctly, they are used by ``FEMap`` to interpolate coordinates, Jacobian etc; since this is not done for inifinite elements anymore, I wander if they are/might be used at other places or if I can remove them right away? 
The alternative is, to not use ``phi_map`` but ``phi_mapx<something>`` to make this finite and account for the extra factor where it is used..

Best regards and stay safe!

**Comment by BalticPinguin** [comment]
ping @roystgnr: any oppinion/comment on this?

**Comment by roystgnr** [comment]
Sorry for letting this drop for so long.

I'm sorry to hear about the divergence (of code paths), but of course long-winded correct code is better than nicely-factored incorrect code every time.

I'm not surprised to hear about the divergence of the Jacobian, but I am surprised that it's a problem: I'd ignorantly presumed that since the divergence was only at the infinite side of the element then there would be some sort of tricky quadrature rule choice that would handle the improper integrals via the right weights.

If no such phi_map exists for which map(qp) = sum(node_i phi_i(qp)), then that's much more disappointing than a little code bloat, but the right thing to do would indeed be to remove phi_map and its derivatives.  No worries about backwards compatibility in a case where the code you're trying to be compatible with is almost certainly calculating an incorrect result.

**Comment by BalticPinguin** [comment]
> Sorry for letting this drop for so long.

Not a problem at all. I continued in this direction and temporarily just removed the phi_map quantities...
And I also was surprised that the Jacobians divergence becomes apparent, but it did.
Actually there is another problem with it: Even if the quadrature rule was 'good' enough so no numerical issues arise, than it would be a quadrature rule assuming polynomials, so it couldn't possibly integrate a Jacobian having some ``1/zeta^n``-dependence...

I hope to come up with a WIP pull request soon; than we can discuss some details where necessary.

**Comment by BalticPinguin** [comment]
fixed by #2506 and #2750 respectively.
