### ISSUE TITLE
BoundaryInfo::sync(): Store parent side index in BoundaryMesh using "extra_integers"

### ISSUE THREAD

**Issue by jwpeterson** [libMesh/libmesh#2457]
This information is almost always useful when creating a BoundaryMesh, and currently the only way to recover it is via `Elem::which_node_am_i()` calls after the fact. It would be better to store this information when it is available during BoundaryInfo::sync(), using the new flexible "extra_integers" storage that was added recently.

**Comment by jwpeterson** [comment]
I plan to make storing these indices optional with the default being "on" but IMO they could also just be non-optional, the way that interior_parents are always stored for BoundaryMeshes...

**Comment by roystgnr** [comment]
My vote is still for optional, but I think I'm starting to come up with reasons why that's my gut hunch:

We sometimes generate multidimensional meshes by starting with a volume mesh and using BoundaryInfo::add_elements to add surface mesh elements on some side(s).  In that case, because of the current limitations of extra_integers storage, we usually don't want to add an integer that's useful on ```N^{2/3}``` boundary elements but would get allocated and manipulated on all $N$, but sometimes that might be worth it, so we'd want to leave it up to the user.  And if we've already done the work to make it optional in that case, we might as well let it be optional in every case.

**Comment by jwpeterson** [comment]
Merged in ef7dd34ad
