### ISSUE TITLE
infinite elements: inverse map

### ISSUE THREAD

**Issue by BalticPinguin** [libMesh/libmesh#2536]
I found another problem in the infinite-element code, this time in the ``inverse_map()`` function: Here the intersection with the base element is computed, respresenting it via the vectors 'point(1)-point(0)' and 'point(2)-point(0)'. The problem with this is that for higher order elements the base is not necessarily flat. (the test case I considered uses the ``build_sphere()``-function.)
This makes the procedure much more complicated and I'd like to ask for some nice ideas to resolve this!?
I don't have anything better in mind that to check in which region the intersection will be (computing the coordinates ``xi`` and ``eta`` is independent of the radius and thus not too complicated). Than I'd compute the (local) plane vectors via the respective nearest nodes.
While this is not very elegant and might lead to a huge amount of code (thus, I'd appreciate any better idea), I even don't know how to do this for ``InfHex18`` and ``InfHex16``: In case of non-planar base, I expect that the element is structured in triangles which each have planar struture (or do you use some interpolation?). If so, one must chose one of the diagonal, but which one is used? I didn't find indications for this in the code...

Sorry for the may-be stupid question.
Best regards,
Hubert

**Comment by roystgnr** [comment]
> the test case I considered uses the build_sphere()-function

If you need a workaround to get a particular problem up and running quickly, you could call all_first_order() and then all_second_order() again to turn a curved-Tet10 sphere mesh into a flattened-Tet10 sphere mesh.  But even that wouldn't work for higher order hexes, and of course it'd be better to actually *fix* this problem rather than just work around it.

> In case of non-planar base, I expect that the element is structured in triangles which each have planar struture (or do you use some interpolation?). 

Interpolation.  Hexes with non-planar sides do have curved sides (bilinear or biquadratic mapping functions from the mater element), not just triangulated sides.

So back to the problem ...

You can use the has_affine_map() method to test that an element (or better yet, a shim element representing just the boundary side) is flat, and fall back to the existing linear algebra in those cheap cases.

In the non-cheap cases ... there might be some exact formula for intersections with biquadratics, but after the Edge3::volume() nonsense recently I'm wary about exact formulae with quadratic elements.  Can we do this with an outer iteration?  FEMap::inverse_map() does handle the case where a 3D point is a little bit away from a 2D element living in 3D space; perhaps we could take advantage of that?  Use the vertices and the linear algebra rule to get an initial guess.  Pass that guess to FEMap::inverse_map(), but leave extra_checks off and don't take the answer as Truth - instead pass the answer *back* to FEMap::map(), project that mapped point onto the line between your original point and the origin, and if the distance moved by that projection step exceeds a tolerance, iterate: pass the projected point back into FEMap::inverse_map() and try again.

I think that ought to converge quadratically, in which case you'll be a few times more expensive in the curved case than in the straight case, but not an order of magnitude more expensive.

**Comment by BalticPinguin** [comment]
Thank you very much! Very helpful comments; I'll take the code @pbauman suggested and adapt it for this case; I think, it is exactly what I need (and more or less follows the suggestion from @roystgnr .
