### ISSUE TITLE
Parametric entities

### ISSUE THREAD

**Issue by stamak777** [libMesh/libmesh#2608]
Hi,

I am generating a ".msh"  file using GMSH (version 4.5.6). I have assigned points, lines, and physical boundaries on my geometry. However, when I run the file in MOOSE, I get the following error:

*** ERROR ***
We don't currently support reading parametric gmsh entities

Does anyone have any suggestions to resolve the issue?

Thanks,

**Comment by jwpeterson** [comment]
I'm not clear on exactly what "parametric" entities in a gmsh file are, but a simple first step would be to read and ignore them rather than erroring out as we do now. Based on the current code:
```
// Now loop over entities
for (std::size_t i = 0; i < num_entities; ++i)
{
  int entity_dim, entity_tag, parametric;
  std::size_t num_nodes_in_block = 0;
  in >> entity_dim >> entity_tag >> parametric >> num_nodes_in_block;
  if (parametric)
    libmesh_error_msg("We don't currently support reading parametric gmsh entities");

  // Read the node tags/ids
  std::size_t gmsh_id;
  for (std::size_t n = 0; n < num_nodes_in_block; ++n)
  {

    in >> gmsh_id;
    nodetrans[gmsh_id] = node_counter++;
  }

  // Read the node coordinates and add the nodes to the mesh
  Real x, y, z;
  for (std::size_t libmesh_id = node_counter - num_nodes_in_block;
       libmesh_id < node_counter;
       ++libmesh_id)
  {
    in >> x >> y >> z;
    mesh.add_point(Point(x, y, z), libmesh_id);
  }
}
```
I'm guessing the parametric entities come after the tags, but you'll have to look at the Gmsh file format spec to know for sure.

Alternatively, if you aren't actually intending to use parametric entities, then maybe you could look into regenerating your Gmsh file so that it doesn't have any... then maybe the reader would work as-is.

**Comment by stamak777** [comment]
It was the Gmsh file format! I had to deselect the parametric coordinates in the GMSH GUI. Thank you for your help!
