### ISSUE TITLE
MeshRefinement with infinite elements: invalid_id

### ISSUE THREAD

**Issue by BalticPinguin** [libMesh/libmesh#2702]
When trying to refine meshes that include infinite elements, I sometimes get into trouble with invalid element ids.
The backtrace is:
````
0: libMesh::print_trace(std::ostream&)
1: libMesh::MacroFunctions::report_error(char const*, int, char const*, char const*)
2: libMesh::DofObject::id() const
3: libMesh::Elem::get_info[abi:cxx11]() const
4: libMesh::Elem::print_info(std::ostream&) const
5: libMesh::FEMap::inverse_map(unsigned int, libMesh::Elem const*, libMesh::Point const&, double, bool, bool)
6: libMesh::InfFEMap::inverse_map(unsigned int, libMesh::Elem const*, libMesh::Point const&, double, bool)
7: libMesh::FEMap::inverse_map(unsigned int, libMesh::Elem const*, libMesh::Point const&, double, bool, bool)
8: libMesh::FEAbstract::compute_node_constraints(libMesh::NodeConstraints&, libMesh::Elem const*)
9: /data/tm162/bin/DSK/master_libmesh-mpich/lib/libmesh_dbg.so.0(+0x27a3d27) [0x7f6de452bd27]
10: /data/tm162/bin/DSK/master_libmesh-mpich/lib/libmesh_dbg.so.0(+0x27efc8e) [0x7f6de4577c8e]
11: libMesh::DofMap::create_dof_constraints(libMesh::MeshBase const&, double)
12: libMesh::System::reinit_constraints()
13: libMesh::EquationSystems::reinit_solutions()
14: libMesh::EquationSystems::reinit()
````
as I see it, the problem is as follows:
In some cases ``node_constraints`` for infinite elements are computed (I set errors for those elements to 0, so I am not sure why this is needed at all), which require computations on the ``side`` of elements.
For this, I have implemented the ``InfFEMap::inverse`` in 2D. Similar to the 3D case, it calls ``FEMap::inverse`` which might not find the correct point (e.g. in case of non-affine maps of the base elements this is expected), leading to ``WARNING:  diff is 2.34146`` etc. 
Within this warning, the ``print_info`` is called which tries to access the ``elem->id()`` which is invalid.

Probably you have some good idea on how to fix this behaviour?
The quick-and-dirty way would be to give the ``base_elem`` a fixed id (e.g. ``0``).
The second way I see is to adjust ``Elem::build_side_ptr()`` such that it assigns a valid id...

Best regards,
Hubert

**Comment by roystgnr** [comment]
> I set errors for those elements to 0, so I am not sure why this is needed at all

You configured with --enable-node-constraints or --enable-everything, and we believed you?  ;-)  When enabled, node constraints get generated for any hanging node.

Could we assign id=DofObject::invalid_id-1 in the constructors in side.h?  I don't want to set id=0, since that'll be confusing to people who expect to be able to look up elem 0 to see what the problem is, and anything *other* than invalid_id itself ought to avoid triggering that assertion.

**Comment by BalticPinguin** [comment]
> You configured with --enable-node-constraints or --enable-everything, and we believed you? ;-)

yes, I used the letter.

> Could we assign id=DofObject::invalid_id-1 in the constructors in side.h? 

That sounds like a good idea; would it be better to set the ``base_elem->id()`` to this right in the ``InfFEMap``-function to avoid assigning ids to all sides generated?

**Comment by roystgnr** [comment]
I'm currently thinking that we actually *ought* to assign ids to all sides generated.  We currently use the invalid_id behavior because we don't want someone to accidentally grab a side id and try to index into the mesh with it and get a different element and eventually have confusing errors later, but if we make the id something that we're confident won't exist in the mesh then we should still catch any invalid indexing in an assertion.  And with that, why not let every side have a valid-but-unindexable id?  The InfFEMap code might be the only place we currently *expect* a high frequency of print_info()-calling-id(), but that could certainly crop up in other use cases as well, and if it does then it'd be nice to not have them die of an overzealous valid_id() assertion either.

**Comment by BalticPinguin** [comment]
I'll close this now. To my mind, this is resolved.
