### ISSUE TITLE
Many inverse_map warnings from fem_system_ex5

### ISSUE THREAD

**Issue by jwpeterson** [libMesh/libmesh#2718]
The failure originally popped up in a `--disable-strict-lgpl` build ([here](https://civet.inl.gov/job/583251/)) but I don't see why it would have anything anything to do with non-LGPL contribs.

To reproduce the error, run:
```
./example-dbg deltat=0.25 n_timesteps=5 time_solver=newmark write_interval=1 solver_quiet=false relative_step_tolerance=1e-3 relative_residual_tolerance=1.e-3 -ksp_type cg -pc_type jacobi 
```
You should see:
```
[0] ../src/fe/fe_map.C, line 2041, compiled Sep 29 2020 at 08:55:03
WARNING:  inverse_map of physical point (x,y,z)=(0.994903, 0.100898,        0) is not on element.
  Elem Information
   id()=485, unique_id()=1549, processor_id()=0
   type()=QUAD9
   dim()=2
   n_nodes()=9
    0  Node id()=1056, processor_id()=0, Point=(x,y,z)=(0.995887, 0.0906107,        0)
    DoFs=(0/0/2112) (0/1/2113) (1/0/2112) (1/1/2113) (2/0/2112) (2/1/2113) 
    1  Node id()=1058, processor_id()=0, Point=(x,y,z)=(0.983179, 0.182644,        0)
    DoFs=(0/0/2114) (0/1/2115) (1/0/2114) (1/1/2115) (2/0/2114) (2/1/2115) 
    2  Node id()=1063, processor_id()=0, Point=(x,y,z)=(  0.9586, 0.178078,        0)
    DoFs=(0/0/2116) (0/1/2117) (1/0/2116) (1/1/2117) (2/0/2116) (2/1/2117) 
    3  Node id()=1052, processor_id()=0, Point=(x,y,z)=( 0.97099, 0.0883454,        0)
    DoFs=(0/0/2102) (0/1/2103) (1/0/2102) (1/1/2103) (2/0/2102) (2/1/2103) 
    4  Node id()=1057, processor_id()=0, Point=(x,y,z)=(0.991773, 0.136203,        0)
    DoFs=(0/0/2118) (0/1/2119) (1/0/2118) (1/1/2119) (2/0/2118) (2/1/2119) 
    5  Node id()=1061, processor_id()=0, Point=(x,y,z)=( 0.97089, 0.180361,        0)
    DoFs=(0/0/2120) (0/1/2121) (1/0/2120) (1/1/2121) (2/0/2120) (2/1/2121) 
    6  Node id()=1062, processor_id()=0, Point=(x,y,z)=(0.966979, 0.132798,        0)
    DoFs=(0/0/2122) (0/1/2123) (1/0/2122) (1/1/2123) (2/0/2122) (2/1/2123) 
    7  Node id()=1059, processor_id()=0, Point=(x,y,z)=(0.983438, 0.089478,        0)
    DoFs=(0/0/2124) (0/1/2125) (1/0/2124) (1/1/2125) (2/0/2124) (2/1/2125) 
    8  Node id()=1060, processor_id()=0, Point=(x,y,z)=(0.979376, 0.134501,        0)
    DoFs=(0/0/2126) (0/1/2127) (1/0/2126) (1/1/2127) (2/0/2126) (2/1/2127) 
   n_sides()=4
    neighbor(0)=nullptr
    neighbor(1)=486
    neighbor(2)=501
    neighbor(3)=564
   hmin()=0.025, hmax()=0.0950835
   volume()=0.00229446
   active()=1, ancestor()=0, subactive()=0, has_children()=0
   parent()=nullptr
   level()=0, p_level()=0
   refinement_flag()=DO_NOTHING
   p_refinement_flag()=DO_NOTHING
   DoFs=
```
and related warnings *many* times in the output. So many, in fact, that we exceeded CIVET's built-in output size limitation:
```
CIVET: Output size exceeded limit (5242880 bytes), further output will not be displayed!
```
which I believe is what actually triggers the failure (the test itself seems to pass). 

Note that you probably do have to run in debug mode to see all these `inverse_map()` warnings, I don't think we do the additional checking in opt mode that is required for them.

Refs #2717 

Tag @roystgnr

**Comment by roystgnr** [comment]
Yeah, I can reproduce this.  I'm trying to see if I can reproduce it on a smaller IGA mesh so I can figure out what's going on.

**Comment by jwpeterson** [comment]
OK, thanks for looking into it. Did you have to build with `--disable-strict-lgpl` in order to see it or was that just a red herring?

**Comment by roystgnr** [comment]
Nah, red herring.

What's going on is we're getting out-of-reference-element inverse map values when we do side reinit on isogeometric elements, where we find xyz for quadrature points on an EDGE3 side and then we map those back to reference points on the QUAD9.  They're not *far* out-of-reference-element, less than 1e-5, but that's worse than the ```2*1e-6``` tolerance we're expecting ... and much more worrisome, when I crank tolerance down to 1e-12, we're *still* out-of-reference-element by nearly 1e-5.

We use FDM to get Bernstein shape derivatives on simplices and weirder elements, but not on quads or lines, so that can't be it.  The rational shape functions are analytic too.  This mesh *itself* seems to have a lot of floating point error (it's supposed to be a perfect annulus, but e.g. the r=1 nodes are at more like r=1+2e-7), but that shouldn't affect the internal consistency at all...

**Comment by roystgnr** [comment]
Well, I've found one bug.  I set the RATIONAL shapes_need_reinit to false, because that would have been fine for Bernstein polynomials limited to p < 3 ... but it needs to be true, because otherwise we end up reusing shape functions that were calculated with nodal weights from a different element.

That was embarrassing.  IIRC I even noticed those warnings at one point and decided to ignore them because what's a 1e-5 error in master coordinates, and maybe FP error is just ballooning our tolerance by a factor of 8 instead of 2 with these weird shape functions?  I should be more paranoid than that.

Fixing that seems to fix the warnings for me.

I'm adding the fix commit to an IGA-kitchen-sink PR, but that one commit should probably be cherry-picked to the release branch too.  I'll try to get the whole PR up and point out the important fix shortly.
