### ISSUE TITLE
"Error: not implemented!" error message change for PBCs 

### ISSUE THREAD

**Issue by freytp** [libMesh/libmesh#2958]
When trying to apply Periodic BCs to two symmetrical surfaces of a 3D mesh in RELAP-7, LibMesh was giving the response: "Error: not implemented!" 

The cause of the problem was found to be sidesets made in Cubit by the user which did not contain perfectly matched node positions. Once this was corrected everything worked. 

Discussion ensued about adding more comprehensive error messaging from LibMesh to help users troubleshoot their input files. @roystgnr agreed to look into the issue and try to revamp LibMesh error messaging. He requested an issue be opened so he could look back at this when he is available.

**Comment by mangerij** [comment]
Ah, interesting. I asked about this yesterday

https://github.com/idaholab/moose/discussions/18261

**Comment by roystgnr** [comment]
There'll be a bit of a delay before the next libMesh submodule update in Moose, but there should be better error messages after that.  I'll try to remember to ping you here again afterwards; I'm like 99% sure that the tests I did with mis-matched PBCs in a standalone libMesh app show the same behavior changes that we'll see from a MOOSE app, but if turns out not to be the case then I can take a second crack at a fix.
