### ISSUE TITLE
Centroid evaluation for certain element types is not accurate

### ISSUE THREAD

**Issue by YaqiWang** [libMesh/libmesh#2976]
Currently the centroid is evaluated as an arithmetic mean of composing vertices. This is correct for simplex, such as triangle or tetrahedra but not accurate for more complicated element shapes, for example quad. In my opinion, we should fix this.

**Comment by roystgnr** [comment]
We should fix this, but we should fix the comments to match.

Before, the function didn't return what it's name said it does.  That's a bug IMHO.  (and a bug that's been there since d7a66045db68b999b3c590360f9ce632ec38c343, so I think this is a new and unbeatable record for Oldest LibMesh Bug Ever!).  But with your PR, it won't return (in the Quad4 case) what it's documentation said it does.  That's still a bug.  Let's update the comment in elem.h to the effect of "may return the element centroid, or may return the average of its nodes"?  Something weasel-wordy like that, so we can get around to updating hex and prism and 2nd order and such elements at some point in the distant future without risking breaking the user contract further.

**Comment by YaqiWang** [comment]
;-) I was just throwing a rock there. Not expecting the commit to be merged by itself. IMO, we should do something similar in `Elem::centroid()` like what we did in `Elem::volume`, i.e. use quadratures for the evaluation. Then we can override each individual types with faster evaluations.

**Comment by roystgnr** [comment]
That's exactly what @jwpeterson suggested - he points out that the linearity of the problem makes the quadrature-based solution surprisingly easy to optimize.

It still won't be nearly as fast as the current "`centroid()`", so we'll want to move that implementation to `vertex_mean()` or something, and transition over the many current use cases that don't require the new level of accuracy ... but at least we'll be able to say that `centroid()` really means *centroid*, at least up to quadrature error, and we can avoid any awful weasel-wordy "sometimes centroid but sometimes not" temporary definition.

**Comment by jwpeterson** [comment]
I will work on adding this soon.

**Comment by jwpeterson** [comment]
Fixed in #2978.
