### ISSUE TITLE
netcdf problems with 1.7.0

### ISSUE THREAD

**Issue by drwells** [libMesh/libmesh#3029]
I get a bunch of link problems with the release candidate like
```
/usr/bin/ld: ./.libs/libmesh_dbg.so: undefined reference to `H5get_libversion'
/usr/bin/ld: ./.libs/libmesh_dbg.so: undefined reference to `nc_inq_grp_full_ncid'
/usr/bin/ld: ./.libs/libmesh_dbg.so: undefined reference to `nc_inq_grpname_full'
/usr/bin/ld: ./.libs/libmesh_dbg.so: undefined reference to `nc_inq_grps'
/usr/bin/ld: ./.libs/libmesh_dbg.so: undefined reference to `nc_inq_grpname'
/usr/bin/ld: ./.libs/libmesh_dbg.so: undefined reference to `nc_inq_grp_parent'
/usr/bin/ld: ./.libs/libmesh_dbg.so: undefined reference to `nc_def_var_deflate'
/usr/bin/ld: ./.libs/libmesh_dbg.so: undefined reference to `nc_def_grp'
/usr/bin/ld: ./.libs/libmesh_dbg.so: undefined reference to `nc_inq_grpname_len'
/usr/bin/ld: ./.libs/libmesh_dbg.so: undefined reference to `nc_inq_grp_ncid'
```

notably, those are all netcdf-4 functions - most of them are in `dgroup.c`, which doesn't seem to be compiled, which makes me think that `USE_NETCDF4` is not being set. However, `dgroup.c` does have a makefile rule generated for it, so I'm not sure why its not getting compiled.

**Comment by jwpeterson** [comment]
Thanks for trying the release candidate. I have not seen this issue, so I'm not sure what the fix would be. We have not updated the bundled netcdf since the last release, but we did update the bundled Exodus, so this could be related. In order for me to reproduce it, would it be possible to share the configure flags that you used?

**Comment by drwells** [comment]
Sure. I checked and I can also reproduce this on master on my mac:

```
#!/bin/bash
set -e

export PETSC_DIR=$HOME/Applications/petsc-3.15.0-homebrew
export PETSC_ARCH=x86_64-opt

mkdir -p objs-debug
cd objs-debug
../configure \
    --prefix=$HOME/Applications/libmesh-dev-debug \
    --with-methods=dbg \
    CC=/usr/local/bin/mpicc \
    CXX=/usr/local/bin/mpic++ \
    --enable-exodus \
    --enable-triangle \
    --enable-petsc-required \
    --disable-boost \
    --disable-eigen \
    --disable-openmp \
    --disable-perflog \
    --disable-pthreads \
    --disable-strict-lgpl \
    --disable-glibcxx-debugging
```

**Comment by roystgnr** [comment]
I've been using the new Exodus pretty regularly, so I wasn't expecting to replicate this ... but yeah, with your configure line (modulo different paths) libMesh master breaks for me the same way.  I'm still trying to figure out why.

Maybe I screwed up the exodus.m4 changes, and explicitly setting `--enable-exodus` (rather than just letting it enable itself by default) is causing it to choose the newest version even if you haven't enabled HDF5 (which doesn't enable itself by default) and then there's a conflict because the new Exodus demands to use NetCDF4 but that's not usable without HDF5?

**Comment by roystgnr** [comment]
> explicitly setting --enable-exodus (rather than just letting it enable itself by default) is causing it to choose the newest version even if you haven't enabled HDF5

It looks like that was indeed the problem.  Sorry the fix took a while to get back to.  Would you confirm that #3034 fixes it for you too?

Thanks for catching this!

**Comment by drwells** [comment]
I will give it a try later today and report back!

**Comment by drwells** [comment]
I verified that this works - thanks!

I don't know if HDF5 is a required dependency of NetCDF4. It may not be - I was able to configure and `config.log` is using NetCDF4, ExodusII 5.22, and not HDF5.
