### ISSUE TITLE
Running the ex1 in the introduction, the Libmesh Performance message does not appear

### ISSUE THREAD

**Issue by Ssssz** [libMesh/libmesh#3101]
Only the Petsc Performance message appears, do I need to install vtk to output Libmesh performance？

**Comment by roystgnr** [comment]
No; you just need to configure libMesh with `--enable-perflog`.

That feature is no longer on by default because it adds a little runtime overhead and it's been somewhat eclipsed by other tools on most systems.  IMHO there's still some cases for which PerfLog is the best choice, but to do approximate performance monitoring with lower overhead it's usually better to use something like perf, Google perftools, or oprofile, and once one of those shows an issue, to do more precise performance monitoring it's sometimes better to use callgrind.
