### ISSUE TITLE
ExodusII_IO::read and export mesh with TET4 elements

### ISSUE THREAD

**Issue by labdala** [libMesh/libmesh#3275]
If  I read a TET4 mesh using Exodus_IO::read and export it into another exodus file, I end up with an empty mesh in Paraview meaning that I can't visualize it. 
Here is a simple code that shows the issue:
```
#include "libmesh/exodusII_io.h"
#include "libmesh/mesh.h"
#include "libmesh/mesh_base.h"
#include "libmesh/elem.h"

int main(int argc, char ** argv)
{
    using namespace libMesh;
    LibMeshInit init(argc, argv, MPI_COMM_WORLD);

    Mesh mesh_fiber(init.comm());
    ExodusII_IO importer(mesh_fiber);
    importer.read("mesh_with_fibers.e");

    mesh_fiber.print_info();

    MeshBase::const_element_iterator el = mesh_fiber.elements_begin();
    const MeshBase::const_element_iterator end_el = mesh_fiber.elements_end();
    for(; el!=end_el; el++)  (*el)->subdomain_id()=1;

    ExodusII_IO exporter(mesh_fiber);
    exporter.write("mesh_fiber_1block.e");

    return 0;
}
```
I believe this is because when we read the mesh this way, the spatial dimension is one:
```
 Mesh Information:
  elem_dimensions()={3}
  spatial_dimension()=1
  n_nodes()=279911
    n_local_nodes()=0
  n_elem()=1437875
    n_local_elem()=0
    n_active_elem()=1437875
  n_subdomains()=7
  n_partitions()=1
  n_processors()=1
  n_threads()=1
  processor_id()=0
  is_prepared()=false
  is_replicated()=true

```

In contrast, using MeshBase::read, I have no problems exporting and visualizing the mesh.

**Comment by jwpeterson** [comment]
Can you try putting
```
mesh_fiber.prepare_for_use();
```
after you read the mesh in, but before you call `print_info()`? When you don't go through the `MeshBase::read` interface, you have to take care of this step yourself. One other comment is related to your setting of subdomain ids. If your mesh contains a mix of different geometric element types (e.g. 3D and 1D elements) then they cannot all be placed in the same subdomain, since we (unfortunately) have a correspondence between "subdomains" in libmesh and "blocks" in exodus, with the latter having the restriction that they can contain only a single geometric element type.

**Comment by labdala** [comment]
Thank you so much @jwpeterson. This works! Is there any reason for why the `prepare_for_use` does not get automatically called when we use ExodusII_IO::read?

**Comment by jwpeterson** [comment]
I think the main reason is that `prepare_for_use()` can be a relatively expensive step (does parallel communication, etc.), so when you are using "lower level" APIs (e.g. constructing the `ExodusII_IO` object yourself) then we assume that you want fine-grained control over exactly when `prepare_for_use()` happens, if at all.

**Comment by labdala** [comment]
Interesting, I didn't know that this was the assumption. I use `ExodusII_IO::read` anytime I need to get elemental variables from an exodus file into a System since `MeshBase::read` can't do it (as far as I know).
Anyways, thank you for your responses. I appreciate it.

**Comment by jwpeterson** [comment]
That's correct, `MeshBase::read()` does not read solutions/variables in general, since it is more the responsibility of the `EquationSystems` object to deal with that. We do have `EquationSystems::read()` but that is only for libmesh's builtin xda/xdr formatted files. The `ExodusII_IO` object evolved over time from being used only for reading/writing meshes, to also writing solutions, and finally to being able to read in solutions, but this support was never integrated with `EquationSystems::read()`, hence the somewhat convoluted approach we have now.
