### ISSUE TITLE
Add routine to fix negative jacobian for all types of elements

### ISSUE THREAD

**Issue by GiudGiud** [libMesh/libmesh#3424]
Negative jacobians in elements can happen for a variety of reasons, one being careless moving around of nodes (for example during a symmetry transform of a mesh, or an extrusion in the wrong direction). It's not illegitimate to want the mesh to be able to repair itself so it can be used. 

It needs to:
- swap some nodes
- update the neighbors

I think this will need to be a routine attribute on the element class

Any idea of other things to do on this?
@dschwen fyi

**Comment by roystgnr** [comment]
For those two specific cases, where we can just flip our node numbering through any symmetry plane and that fixes the problem, this sounds like a great idea for a new method.  I'd say `flip()` should be in an `ElemModification` namespace rather than in `Elem`, but that's a mistake we've been making one new method at a time for at least a decade so there's no reason to change right now.  Maybe one of these years I'll move everything that should be moved and turn the original methods into deprecated shims.

We could at least put the "do it on every Elem in the mesh" utility method (and the underlying "do it on every element in the range" method) in `MeshModification`.

We'll need to swap element child pointers on refined meshes, too; there's some code in libMesh that relies on internal standards like "vertex v is also vertex v on child v" that would break if we reordered nodes but not children.

For "careless moving around of nodes" in the general case, where the mesh self-overlaps, this isn't a problem with a local solution; displacement sufficient to tangle an originally-valid reference mesh requires a tricky global solve to properly untangle.  Long ago our variational smoother code used to be able to handle that, but we never got test coverage of it and at some point it regressed.

**Comment by roystgnr** [comment]
> I'd say flip() should be in an ElemModification namespace

Looking at implementing this (it's a nice trivial thing to work on while I'm feeling a bit under, and I'm waiting for tests to run on other things before I put up the next submodule update), I'm just wrong here.  A virtual function is faster and even simpler than an Elem-type-independent method would have been.

**Comment by GiudGiud** [comment]
Are you implementing this?
It s on my list for tonight but running late on discussions support and if you're doing it I can yield it.

**Comment by roystgnr** [comment]
Yeah, I'm taking a crack at it now.

**Comment by roystgnr** [comment]
What did you have in mind for edges in 2D/3D and faces in 3D?  I'm leaning towards "don't even bother unless they're restricted to the X axis / the XY plane (respectively)"; we already do more complicated Jacobian calculations to handle lower dim elements in higher dim space.

**Comment by jwpeterson** [comment]
If I recall correctly, we can't get negative Jacobians on 2D elements living in 3D space (via FE calls), because of the details of the way JxW is computed... So how are you actually planning to tell when an Elem has become inverted in this case? The last time we discussed this we considered having a "reference" normal direction, so that one could compute a signed area, but this idea had some issues as well e.g. how to choose the normal direction when not in a (x,y) planar mesh.

**Comment by roystgnr** [comment]
First crack is in https://github.com/roystgnr/libmesh/tree/elem_flip but it's still completely lacking in testing; running out of spare time this afternoon and I'm not sure I'll make it back to this before Monday.
