### ISSUE TITLE
How to obtain a more detailed description of the FEfamily type ?

### ISSUE THREAD

**Issue by tu1620808124** [libMesh/libmesh#3478]
For example, if I want to use DG element, there are MONOMIAL , L2_HIERARCHIC , and L2_LAGRANGE. And this hard for me to know the details between this three types.

**Comment by roystgnr** [comment]
These three are fairly simple types: the `MONOMIAL` basis functions are just monomials in master-element (xi, eta, zeta) coordinates, the `L2_LAGRANGE` basis functions equal the usual `LAGRANGE` *shape* functions on an element but don't extend into neighbor elements, and likewise for `L2_HIERARCHIC` vs `HIERARCHIC`.

But because of the tricky Curiously Recurring Template Pattern optimization, we don't exactly have our usual one-class-per-header spots to put documentation.  What we have (which is embarrassingly terse, isn't it?) is in fe.h, attached to the syntactic sugar (shim subclasses/typedefs) for each type.

**Comment by roystgnr** [comment]
Hmm.. in fact, neither the documentation *nor* what I just said covers one of the most important distinctions here: because they need to match up with the full order C0 spaces, on tensor product geometric elements the `L2_` finite element spaces span the space of all tensor-products of 1-dimensional polynomials up to a given degree p, while the `MONOMIAL` space only spans the space of d-dimensional polynomials of degree p.  A cubic hex would have 64 shape functions in the former case, only 20 in the latter.
