### ISSUE TITLE
Hardcoded /usr/include/tirpc path

### ISSUE THREAD

**Issue by mboisson** [libMesh/libmesh#3709]
Your configure script tests for XDR in a hard-coded system path `/usr/include/tirpc`, which is not the right location to check for this on our system. Any way to include a `TIRPC_DIR` environment variable or something similar ?

```
              { $as_echo "$as_me:${as_lineno-$LINENO}: checking for XDR support in /usr/include/tirpc" >&5
$as_echo_n "checking for XDR support in /usr/include/tirpc... " >&6; }```

**Comment by roystgnr** [comment]
The original idea was that RPC and XDR headers were standardized in the **1980s** so it would be reasonable to just assume they're in the compiler's search paths already.  But they never made it into POSIX so that wasn't a reasonable assumption in the end.

The second idea was that, okay, some systems move them around, but at least there's a new pseudostandard place.  But that only works for users who can easily get software installed, which means it's not reasonable for all HPC systems.  I've been pointing out how to manually override compiler and linker flags a couple times lately as a workaround.

And the third idea was the least reasonable of the three: "I should fix this but I'm too busy with other things and too lazy when I'm not busy".  Thanks for beating me to it!

**Comment by jwpeterson** [comment]
> That looks like a test which was specific to Fedora 28.

While working on #3711 I realized Ubuntu 22 (and probably previous releases) is also using `/usr/include/tiprc` now, so seems like there is at least some standardization around that.
