### ISSUE TITLE
Enabling threaded print of element information

### ISSUE THREAD

**Issue by GiudGiud** [libMesh/libmesh#3725]
The get/print_info on elem is great as it gives a ton of information. It's probably mostly meant for debugging. But in MOOSE we call it for the regular Moose::stringify(Elem) and that can be conceivably used in a threaded region. 

it is however not thread safe as the enum_to_string populates a map the first time it s called I believe

A few ideas for a fix / change:
- make get_info or the enum_to_string balk at being called in a threaded region that way the problem does not appear again
- create a thread-safe get_reduced_info that gives less information and that MOOSE uses for stringify(elem)

**Comment by roystgnr** [comment]
Oh, that's nasty.

I think the real fix is to make `enum_to_string` stop relying on just-in-time creation of those maps.  I'm sure the existing code is little more than an artifact of static maps being a pain to initialize in C++98; we should have upgraded it as soon as we started requiring compilers with `std::initializer_list` support.

Ideally the constructor itself would be at compile-time, since there's nothing that varies from run to run about it ... but even `constexpr std::vector` is a C++20 thing and I don't see any `constexpr std::map` on the horizon.  No matter; these are such small maps that just initializing a couple dozen of them in static constructors should be negligible cost, and they don't depend on any other objects so there should be no static constructor initialization order to worry about.

...

I hope?  We don't have any other static objects that depend on these maps, surely?  I'll need to leave a `libmesh_assert(!foo.empty())` in the conversion routines to guard against that...
