### ISSUE TITLE
Issue with libmetis.so.5 while make install

### ISSUE THREAD

**Issue by AlbertoBittes** [libMesh/libmesh#3890]
Hello,
I'm trying to install libmesh by following the procedures of the readme.
I've installed petsc and other dependencies (e.g. trilinos, hdf5) via linux distributions.
I am facing a couple of issues that I would need to solve:
1. configure is not finding some dependencies like trilinos or hdf5 even though they are installed in standard paths, and I cannot activate the parallel mesh feature even with the --enable-distmesh flag during configure. Here I have the feeling I'm doing something wrong, but the readme states that configure should be able to find automatically external packages.
2. make gives  the  following error:

make[1]: Entering directory '/home/bitteal/libmesh/build'
  CXXLD    fparser_parse-opt
/usr/bin/ld: gk_cur_jbufs: TLS definition in /lib/x86_64-linux-gnu/libmetis.so.5 section .tdata mismatches non-TLS definition in ./.libs/libmesh_opt.so section .data
/usr/bin/ld: /lib/x86_64-linux-gnu/libmetis.so.5: error adding symbols: bad value
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:14193: fparser_parse-opt] Error 1
make[1]: Leaving directory '/home/bitteal/libmesh/build'
make: *** [Makefile:33677: all-recursive] Error 1

Here I attach the config log file:
[config.log](https://github.com/user-attachments/files/15988995/config.log)

Thank you!

**Comment by roystgnr** [comment]
> the readme states that configure should be able to find automatically external packages.

This might be the README being out of date.  I'm afraid our current status there is probably a bit mixed: a bunch of old configure code that's designed to automatically find external packages in common lib directories (because we wanted to be user-friendly to people who had packages they wanted to use there) combined with a bunch of newer configure code that's designed to only find external packages as specified by environment variables and/or configure arguments (because we realized we needed to be user-friendly to people who had *outdated versions* of the packages they wanted to use there).

Our user base gradually changed from "we all can run sudo or are friends with someone who can" to "the supercomputer administrators will not deign to speak with us today; we're number 28410 in the queue"; the former group usually had whatever they needed in /usr/lib but the latter group had to be able to avoid it.

Case in point:

> /lib/x86_64-linux-gnu/libmetis.so.5 section .tdata mismatches

I'd need more information to be sure, but I'm guessing that our `configure` either built a libmetis for you from our `contrib` directory or detected a libmetis in your `$PETSC_DIR`, but then whichever version it used wasn't compatible with the one sitting in `/lib` there, and some other autodetection added that library path to your compiler flags anyway to try to get at a different system-installed library.  I'd first try telling libMesh `configure` explicitly to use `--with-metis=` and `--with-metis-include=` pointing to the system library, and similarly for PETSc if it's building its own too.

**Comment by AlbertoBittes** [comment]
Thank you, the problem with libmetis is solved this way.
Still struggling with other points though, but I think it's matter of playing with the various configuration options.

**Comment by roystgnr** [comment]
Thanks; I'll mark this as closed then.

Normally "just try out configuration options" isn't a bad plan, but today you might want to report any issues sooner rather than later; tomorrow I start a vacation and my response rate should be dropping drastically.
