### ISSUE TITLE
Import from MSH-File: 

### ISSUE THREAD

**Issue by grunerjmeier** [libMesh/libmesh#3899]
Dear Community,

When importing the gmsh-file given in [1] into Moose, "PointA" gets assigned wrong coordinates. The FE elements (volumes, plates and beams) are imported fine.

[1] https://github.com/grunerjmeier/Suzanne/blob/117edc4794f077663d7b55f0292e5554ad0fb4db/suzanne.msh

As per the MSH-File, "PointA" should be to top of the head of Suzanne (coordinates '0 3.4988 9.28'). Please see image below.
https://github.com/grunerjmeier/Suzanne/blob/117edc4794f077663d7b55f0292e5554ad0fb4db/suzanne.msh#L35

Instead in Moose PointA is set to (-1.05469,  3.65505, -14.0167):
```
FileMeshGenerator 'file':  Mesh Nodesets:
FileMeshGenerator 'file':   Nodeset 1 (PointA), 1 nodes
FileMeshGenerator 'file':    Bounding box minimum: (x,y,z)=(-1.05469,  3.65505, -14.0167)
FileMeshGenerator 'file':    Bounding box maximum: (x,y,z)=(-1.05469,  3.65505, -14.0167)
FileMeshGenerator 'file':    Bounding box delta: (x,y,z)=(       0,        0,        0)
```

The msh file is imported to Moose via
```
[Mesh]
  [file]
    type = FileMeshGenerator
    file = "suzanne.msh"
    show_info = true
  []
[]
```

![image](https://github.com/libMesh/libmesh/assets/57180520/81f5d112-f193-408a-9edd-6e55f92ff169)

**Comment by roystgnr** [comment]
Looks like you've got a GMSH 4.1 format file, and it's hitting our `if (version >= 4.0)` block, but people are saying [they've changed the format from 4.0 to 4.1](https://github.com/HomerReid/scuff-em/issues/184)?

If there are major changes then I don't know if we'll have time to update to them; if you could try converting your file to 4.0 then I'd love to know if it's still breaking or not and I'm sure you'd love to know if not.

But that might be a red herring - looking at [the current format](https://gmsh.info/doc/texinfo/gmsh.html#MSH-file-format) I don't see anything major out of place for point $Entities or $Elements.

And now I do see what looks like the cause of the discrepancy, in the way we're treating their many numberings:  ["PointA" is physicalTag 1](https://github.com/grunerjmeier/Suzanne/blob/117edc4794f077663d7b55f0292e5554ad0fb4db/suzanne.msh#L6), and [the entity with physicalTag 1 is a point with pointTag 1 at (0 3.498798 9.28)](https://github.com/grunerjmeier/Suzanne/blob/117edc4794f077663d7b55f0292e5554ad0fb4db/suzanne.msh#L35), but then when we get to the $Elements block we see that [the nodal element with elementTag 1 has nodeTag 1](https://github.com/grunerjmeier/Suzanne/blob/117edc4794f077663d7b55f0292e5554ad0fb4db/suzanne.msh#L39685), and we assume that because that nodeTag matches the previous pointTag it's the place we want to put the pointTag's boundary condition, at [the node with nodeTag 1 at (-1.054688 3.655048 -14.01674)](https://github.com/grunerjmeier/Suzanne/blob/117edc4794f077663d7b55f0292e5554ad0fb4db/suzanne.msh#L19873)

I'm guessing this nodeTag/pointTag conflation works for most files so nobody ever noticed before?  There's a pre-GMSH-4.0 comment noticing a bit of confusion right when we assign nodal boundary ids, but even that is just about the elementTag vs nodeTag there, not nodeTag vs pointTag.

If I've identified the problem correctly then the solution is to keep a hash map of points-to-nodes, keying on location rather than any sort of numbering, and for nodal BCs use that rather than just our gmsh-to-libmesh-node-numbers map.  I could try that.  Could you generate a smaller mesh that exhibits the same problem, so we can throw it in a unit test?

**Comment by grunerjmeier** [comment]
Dear roystgnr,

Thank you for your answer and looking into this problem.

With a heavy heart, I removed Suzanne from the model and greatly reduced the number of elements. The msh file is now 3’166 bytes in size: [block.msh](https://github.com/grunerjmeier/Suzanne/blob/9548ab54911336d38a30b725f02d896952757a4c/block.msh)

The geoemtry now looks like this:
![image](https://github.com/libMesh/libmesh/assets/57180520/30e5cd6c-52f8-4cbb-af85-9bc1acfbeda0)

Gmesh v4.12.2 loads this file without problems and shows PointA, PointB, and PointC (and all the other elements) at the right location.
<img width="355" alt="block in gmsh" src="https://github.com/libMesh/libmesh/assets/57180520/881d7355-6aa6-400b-8226-ee4d41fbbeec">

Loading this file into Moose places PointA, PointB, and PointB at the wrong locations. Please see my corresponding Moose input file below. So we now have a much smaller test file able to reproduce.

<details><summary>Code Block: Moose Input File</summary>
<p>

```
[Mesh]
  [file]
    type = FileMeshGenerator
    file = "block-gmsh.msh"
    show_info = true
  []
[]

[Problem]
  solve = false
[]

[Executioner]
  type = Steady
[]

[AuxVariables]
  [dummy]
    order = FIRST
  []
[]

[Outputs]
  exodus = true
[]
``` 

</p>
</details> 

`show_info` places the points here (coordinates do not match):

```
FileMeshGenerator 'file':  Mesh Nodesets:
FileMeshGenerator 'file':   Nodeset 1 (PointC), 1 nodes
FileMeshGenerator 'file':    Bounding box minimum: (x,y,z)=(     -14,        0,      -14)
FileMeshGenerator 'file':    Bounding box maximum: (x,y,z)=(     -14,        0,      -14)
FileMeshGenerator 'file':    Bounding box delta: (x,y,z)=(       0,        0,        0)
FileMeshGenerator 'file':   Nodeset 2 (PointA), 1 nodes
FileMeshGenerator 'file':    Bounding box minimum: (x,y,z)=(     -14,      -10,      -14)
FileMeshGenerator 'file':    Bounding box maximum: (x,y,z)=(     -14,      -10,      -14)
FileMeshGenerator 'file':    Bounding box delta: (x,y,z)=(       0,        0,        0)
FileMeshGenerator 'file':   Nodeset 3 (PointB), 1 nodes
FileMeshGenerator 'file':    Bounding box minimum: (x,y,z)=(       0,      -10,      -14)
FileMeshGenerator 'file':    Bounding box maximum: (x,y,z)=(       0,      -10,      -14)
FileMeshGenerator 'file':    Bounding box delta: (x,y,z)=(       0,        0,        0)
```

I'll try to repeat your analysis of the input file in a later comment.

**Comment by grunerjmeier** [comment]
Dear roystgnr,

I'll try to repeat you analysis with "PointB" of the [simplified input file](https://github.com/grunerjmeier/Suzanne/blob/9548ab54911336d38a30b725f02d896952757a4c/block.msh). Conclusions and subsequent questions at the end.

**$PhysicalNames**
In [line 8](https://github.com/grunerjmeier/Suzanne/blob/9548ab54911336d38a30b725f02d896952757a4c/block.msh#L8), "PointB" is defined for Dimension=0 as PhysicalTag=3.
`0 3 "PointB"`

**$Entities**
In the points-subsection of the entities section PointB is represented in [line 29](https://github.com/grunerjmeier/Suzanne/blob/9548ab54911336d38a30b725f02d896952757a4c/block.msh#L29).
`3 -14 15 -14 1 3`
For PointTag=3 the coordinates (x=-14, y=15, z=-14) and only one physical Tag (PhysicalTag=3) is given.

**$Nodes**
In the $Nodes section is only one entity block is given. And this entity block is for entityDim=3 (the volume "Base"). There is no reference in the $Nodes section to PointB or any other lower-dimensional block. (ups?!?)

**$Elements**
In the $Elements section, PointB is represented in [line 148](https://github.com/grunerjmeier/Suzanne/blob/9548ab54911336d38a30b725f02d896952757a4c/block.msh#L148) and [line 149](https://github.com/grunerjmeier/Suzanne/blob/9548ab54911336d38a30b725f02d896952757a4c/block.msh#L149).
```
0 3 15 1
3 3
```
This assigns the element type 15 (1-node-point), elementTag=3, and nodeTag=3 (Wait! "nodeTag=3"?). This confirms your analysis.

**Conclusions and subsequent questions**
My msh-file seems to be obviously not fully consistent. In [line 149](https://github.com/grunerjmeier/Suzanne/blob/9548ab54911336d38a30b725f02d896952757a4c/block.msh#L149) nodeTag=3 is assigned, but nodeTag=3 applies to a node of the volume "Base" at a diffent location.  I did not realize this before - sorry!

I will change my input files, so they point to the correct nodeTag in the $Nodes section. I tried that with block.msh and it seems to work!

On the other hand: Gmsh is reading my file "correctly" and seems to just ignore [line 149](https://github.com/grunerjmeier/Suzanne/blob/9548ab54911336d38a30b725f02d896952757a4c/block.msh#L149) with the reference to nodeTag=3. My interpretation is, that Gmsh is just using the coordinates given in the $Entities section (and ignores the nodeTag). Should libmesh adopt this behaviour? Or should libmesh check the coordinates in $Entities against the node coordinates and error if there is no match?

Please allow me two more questions: 

- Shoud "PointA", PointB", and "PointC" also be marked with "lower_dimensional_block"?
- Is it correct, that the $Nodes-section does not contain any items for the PhysicalNames marked with "lower_dimensional_block"? I dont want to have two or more nodes at the same location.

**Comment by roystgnr** [comment]
> Should libmesh adopt this behaviour?

I think so.  We assumed at some point that a pointTag and a nodeTag were basically the same thing (since for us a Node is just a Point with some degree of freedom indexing information and incoming connectivity, and since we don't have any way to apply 0-D boundary conditions to anything but a Node anyway), but that seems to have been an incorrect assumption.

> Or should libmesh check the coordinates in $Entities against the node coordinates and error if there is no match?

We're going to have to do this *too* - if we try to look up a node by coordinates and we don't find one then I don't think there's any way for us to load that mesh.

> Shoud "PointA", PointB", and "PointC" also be marked with "lower_dimensional_block"?

Yes, or no, depending on what you want to do with them.  If you want them to exist as `NodeElem` elements, then yes (I'm not sure if we support this for 0D, but it could be added easily enough if not); if you only want them to exist as nodes of higher-dimensional elements (as well as boundary conditions), then no.  IIRC this is just a libMesh extension someone added; the GMSH format itself doesn't do anything with that tag because it doesn't make that distinction.  (which worries me, because if they ever make their parser stricter then suddenly files with our extension are going to start breaking there...)

> Is it correct, that the $Nodes-section does not contain any items for the PhysicalNames marked with "lower_dimensional_block"? I dont want to have two or more nodes at the same location.

You've got 1D and 2D lower_dimensional_block elements there; those should be referencing Entities which reference Elements which reference Nodes; not having a direct reference to Nodes should be correct.

**Comment by grunerjmeier** [comment]
Dear roystgnr,

Thanks again for your extensive answer! 

Jörg

**Comment by roystgnr** [comment]
> I'm not sure if we support this for 0D, but it could be added easily enough if not

After checking: we don't; it's only supported for 1D and 2D right now.

> this nodeTag/pointTag conflation

The more I think about this the more it bothers me.  The GMSH format specification does the perfectly analogous thing with curveTag, surfaceTag, and volumeTag: a tag integer defines the $Entities getting physicalTag(s) assigned, and then that integer matches the entityTag in the $Elements block.  They all have geometric data (bounding boxes) attached, and in all those cases the correct thing to do is *ignore* that geometric data and just pay attention to the tags.  So why are we incorrect in the node case, when we do the same thing?!

I'm starting to think that the only safe thing to do here is to add an error when we detect an inconsistency.  If we see a file that wants to add a nodal boundary condition at node N at point P, and we see that node N isn't at point P, we're basically doomed at that point, aren't we?  It's easy to imagine users or software intending one interpretation or intending the other, and if we can't figure out which then my proposed solution of "ignore N and respect P" is just going to break for a *different* subset of users than our current "ignore P and respect N" code.

Your thoughts?  I'm going to add the error checking now; if I'm wrong and these aren't really inconsistencies in some sense then I can perhaps downgrade that to a warning later.

**Comment by grunerjmeier** [comment]
> Your thoughts? I'm going to add the error checking now

I fully agree with your comment. I am also in favour of displaying an error here if the data is inconsistent. Anything else would be guesswork, which in some cases is correct and in other cases makes troubleshooting more difficult and produces "issues" in this github-repo.

**Comment by roystgnr** [comment]
Thanks.  The obvious downside here is that we may have users who are getting their desired solutions from "ignore P and respect N" and who are going to have to tweak their $Entities entries to get such files working again.  I think that's a price worth paying to avoid other users silently getting incorrect results, though.
