### ISSUE TITLE
Please fix bash shebangs in scripts

### ISSUE THREAD

**Issue by yurivict** [libMesh/libmesh#3988]
For example, the file examples/reduced_basis/reduced_basis_ex6/run.sh has "#!/bin/bash" and the correct shebang is "#!/usr/bin/env bash".

On BSDs and some other systems bash isn't in /bin/bash and it should be resolved through the PATH variable.

**Comment by roystgnr** [comment]
That's a good idea, for scripts where we do need bash ... although I'll bet there's a lot more of our scripts (possibly all of them?) where either we don't need bash or we accidentally introduced bash-isms out of laziness.  We should probably stop requiring bash rather than sh for those.

2 questions:

Is `#!/usr/bin/env sh` still the best shebang in that case?  I see that `sh` isn't guaranteed to be in `/bin` by POSIX, but it seems like that's probably a safer bet than `env` being in `/usr/bin`.

Is there a better alternative to `dash` for testing POSIX compliance?  That's `/bin/sh` on Ubuntu and the package literally calls it "POSIX-compliant shell", but I'm reading (and verifying) that `dash` still supports some non-POSIX idioms I use habitually like `echo -n`.

**Comment by yurivict** [comment]
> Is #!/usr/bin/env sh still the best shebang in that case?

No, "#!/bin/sh" should suffice.

> Is there a better alternative to dash for testing POSIX compliance?

[ShellCheck](https://www.shellcheck.net/) is supped to be a good way to check POSIX compatibility.
[This](https://unix.stackexchange.com/questions/48786/how-can-i-test-for-posix-compliance-of-shell-scripts) StackExchange answer suggests the same.

Additionally, FYI, in case you didn't know, shell interpreters support the "STRICT" mode when they don't tolerate some borderline erroneous behavior or the code.

The STRICT mode can be turned on with this command: ```set -euo pipefail```

I think you should use it in all shell scripts.
