### ISSUE TITLE
Allow addition/removal of new systems after init() has been called

### ISSUE THREAD

**Issue by permcody** [libMesh/libmesh#437]
The title is self-explanatory. In terms of MOOSE priorities we need the former but not the latter at this time.

**Comment by permcody** [comment]
@andrsd  - Do you have a test case for this feature or better direction of what you may need?

**Comment by andrsd** [comment]
Our projection transfer is waiting for this to be implemented. Then it will either work right out of the box or will need to be finished (I think I did not finish the work because of this, so I lean towards the latter case). So, starting with `tests/transfers/mutliapp_projection_transfer/tosub_master.i` would be a good... start ;-)

**Comment by roystgnr** [comment]
Actually, I appear to have been foolishly running "make check" in a different checkout; it looks like my own unit test might have been enough to trigger the failure after all.  I'll start with that.

**Comment by roystgnr** [comment]
We're passing unit tests now, so I'll give tosub_master.i a shot.  I just need to remove the "deleted" line corresponding to it in tests/transfers/multiapp_projection_transfer/tests before running "make test"?

**Comment by permcody** [comment]
Right, alternatively you can just run moose_test manually on that input
file.

Thanks

**Comment by jwpeterson** [comment]
I think this is done, but feel free to reopen if not.
