### ISSUE TITLE
Don't allow duplicates in BoundaryInfo

### ISSUE THREAD

**Issue by permcody** [libMesh/libmesh#706]
It looks like we are creating duplicate entries in the `BoundaryInfo` data structure through the extrusion process. I haven't dug in yet to see why but it's fairly easy to see it after running an extrusion and running `BoundaryInfo::print_info()`

See https://github.com/idaholab/moose/issues/3554

Output of `print_info()`
```
Side Boundary conditions:
-------------------------
  (Elem No., Side No., ID)      
  (0, 1, 0)
  (0, 1, 0)
  (0, 4, 3)
  (0, 0, 6)
  (16, 1, 0)
  (16, 1, 0)
  (16, 4, 3)
  (32, 1, 0)
  (32, 1, 0)
  (32, 4, 3)
  (48, 1, 0)
  (48, 1, 0)
  (48, 4, 3)
  (64, 1, 0)
  (64, 1, 0)
  (64, 4, 3)
  (80, 1, 0)
  (80, 1, 0)
  (80, 4, 3)
  (80, 5, 7)
  (1, 1, 0)
  (1, 1, 0)
  (1, 0, 6)
```

**Comment by jwpeterson** [comment]
`BoundaryInfo::_boundary_side_id` is a `std::multimap`, since we want to allow the same element to have multiple sides (or the same side) in different sidesets.  One fix for this issue would be to detect duplicates during the call to `BoundaryInfo::build_side_list` and not output them.  Or we could try to detect the duplicates at insertion time, assuming that would not change the algorithmic complexity of adding sides too badly.

**Comment by permcody** [comment]
Here's a separate but related issue. If we completely clear an existing ID from the data structure (something that will happen if we renumber a boundary condition). The BoundaryInfo will maintain that empty ID even though it's not written to the Exodus file. Perhaps we can clean that up automatically too? If not, we can just update this method:
https://github.com/idaholab/moose/blob/devel/framework/src/mesh/MooseMesh.C#L1658
to explicitly remove the renamed id.

**Comment by jwpeterson** [comment]
Yeah, if `BoundaryInfo::remove_side` removes the last side from a sideset, something should probably update the `_boundary_ids` data structure...

**Comment by jwpeterson** [comment]
Just double-checked, and both versions of `BoundaryInfo::add_side()` already check for duplicates before adding them to the `_boundary_side_id` data structure... so something else must be adding them.

**Comment by roystgnr** [comment]
Checking for duplicates everywhere should actually be *good* for complexity in cases where they might crop up - having a smaller tree in the multimap would make up for hitting the tree harder before inserts.

I can't see how we'd be creating duplicates, though; doesn't every access to that data structure go through add_side()?

**Comment by jwpeterson** [comment]
> I can't see how we'd be creating duplicates, though; doesn't every access to that data structure go through add_side()?

Yes it does, this is where I'm currently stuck...

**Comment by permcody** [comment]
One more...

@YaqiWang mentioned the following in https://github.com/idaholab/moose/issues/3554
1. we currently did not check the element type of remapped blocks. Users could remap two blocks in different element type into the same block, which should be error out during extrusion but not now;

I can certainly add a check on the MOOSE side to prevent this, but do we want to catch this on the libMesh side instead?

**Comment by jwpeterson** [comment]
On Wed, Nov 4, 2015 at 10:05 AM, Cody Permann <notifications@github.com>
wrote:

> One more...
>
> @YaqiWang <https://github.com/YaqiWang> mentioned the following in
> idaholab/moose#3554 <https://github.com/idaholab/moose/issues/3554>
> 1. we currently did not check the element type of remapped blocks. Users
> could remap two blocks in different element type into the same block, which
> should be error out during extrusion but not now;
>
> I can certainly add a check on the MOOSE side to prevent this, but do we
> want to catch this on the libMesh side instead?
>

I don't think so.  There's nothing intrinsically wrong with having elements
with different geometric type in the same block as far as libmesh is
concerned.  This is a restriction of the Exodus file type.  Since that file
format is used so extensively in MOOSE, it might be worth checking for it
there.

-- 
John

**Comment by jwpeterson** [comment]
I think I understand the problem: we are calling this version of `add_side()` that takes a vector of ids:
```
void BoundaryInfo::add_side(const Elem* elem,
                            const unsigned short int side,
                            const std::vector<boundary_id_type>& ids)
```
and it doesn't check whether the entries in the passed-in `ids` vector are unique.  In this particular example, we happen to be passing in `ids=={0, 0}`. Then, since we only call `equal_range` once outside the loop over ids, we add the same element with the same side and ID once for each repeated entry in ids.

One fix would be to create a temporary `std::set` out of the `ids` vector.  It probably should have been a `std::set` in the first place, but I don't want to change the API now...

**Comment by jwpeterson** [comment]
The same issue exists in:
```
void BoundaryInfo::add_node(const Node* node,
                            const std::vector<boundary_id_type>& ids)
```

**Comment by pbauman** [comment]
> One fix would be to create a temporary std::set out of the ids vector. It probably should have been a std::set in the first place, but I don't want to change the API now...

Maybe do the fix, deprecate those functions and add new API and use it internally?

**Comment by jwpeterson** [comment]
> Maybe do the fix, deprecate those functions and add new API and use it internally?

Sounds reasonable.

**Comment by roystgnr** [comment]
Agreed, @pbauman.

Not it!

**Comment by pbauman** [comment]
Crap, I just volunteered myself didn't I.

**Comment by jwpeterson** [comment]
> Crap, I just volunteered myself didn't I.

No, I'm almost done with it.
