### ISSUE TITLE
Investigate logic issues in threads.h

### ISSUE THREAD

**Issue by jwpeterson** [libMesh/libmesh#838]
This is tricky since, as @permcody pointed out, we can have multiple threading models enabled simultaneously.  Imagine a case where both `LIBMESH_HAVE_OPENMP` and `LIBMESH_HAVE_PTHREAD` are defined.  Then, the following code from threads.h will call `pthread_join()` while never having called `pthread_create()`...

```
#ifdef LIBMESH_HAVE_OPENMP
#pragma omp parallel for schedule (static)
#endif
  for(unsigned int i=0; i<n_threads; i++)
    {
#if LIBMESH_HAVE_OPENMP
      run_body<Range, Body>((void *)&range_bodies[i]);
#elif LIBMESH_HAVE_PTHREAD
      pthread_create(&threads[i], libmesh_nullptr, &run_body<Range, Body>, (void *)&range_bodies[i]);
#endif
    }

#if LIBMESH_HAVE_PTHREAD
    for (int i=0; i<static_cast<int>(n_threads); i++)
      pthread_join(threads[i], libmesh_nullptr);
#endif
```

I suggest that we only allow a single threading model to be active at a time.  If the user requests a specific one, we give them that (if available) otherwise there is a specific hierarchy that we use to choose *the* threading model that is active, and disable the others.

**Comment by friedmud** [comment]
Yep.  @permcody broke it.

Right here:  https://github.com/libMesh/libmesh/commit/bca60c6aa668b84b47003106f31823375a3206b2#diff-da1d293dd8ccb6bcfd350add22c3e363L558

**Comment by friedmud** [comment]
Oh - but I do agree that this is really a symptom of the underlying issue that we allow for multiple models to be turned on... but there is an implicit preference hierarchy that's built into the code tbb>openmp>pthreads.  That hierarchy should really be moved to configure time and enforced.

**Comment by friedmud** [comment]
While we're at it we should make sure the "pure serial" case works (i.e. without ANY threading model!).

**Comment by jwpeterson** [comment]
Agreed.

**Comment by permcody** [comment]
Well it was already incorrect. I was just maintaining status quo. ;)

**Comment by friedmud** [comment]
How was it incorrect before?  It had `#if !LIBMESH_HAVE_OPENMP` which is exactly right.

We were already within a `#ifdef LIBMESH_HAVE_PTHREAD` (See https://github.com/libMesh/libmesh/blob/bca60c6aa668b84b47003106f31823375a3206b2/include/parallel/threads.h#L330  ) so that line of code was exactly right and didn't need to be modified...

**Comment by friedmud** [comment]
However, investigating that last part did remind me of something.  Currently the OpenMP interface _depends_ on Pthreads.  For instance, we use all of the pthread locking mechanisms when running with OpenMP.  I think that can be changed... but it's just going to require quite a bit of work.

Each threading model should be split out into its own header file so that it's easy to see that each model specifies all of its own threading objects...

**Comment by permcody** [comment]
Nothing syntactic. The mutex was the problem. You can't use a spin mutex in
a recursive context. We seemed to be getting away with it, but it could
result in undefined behavior.

**Comment by permcody** [comment]
Right, splitting these up will be a lot less error prone.

**Comment by friedmud** [comment]
My point is that for right now we should put the original `#if !LIBMESH_HAVE_OPENMP` there... because the code is definitely not right currently.

**Comment by permcody** [comment]
Right, this immediate issue should be fixed regardless of the longer term plan to fix the threading design.

I recall not liking the "not" logic because of the multiple independent models. I realize that this particular section of code can't be reached if you have TBB due to a different `#ifdef` elsewhere in this class but if it could, or that other `#ifdef` changed this "not" logic wouldn't be right either. The whole class is very brittle and yes, I take responsibility for the current flub.

**Comment by friedmud** [comment]
And I take responsibility for creating the mess :smile: .  I should have refactored this long ago when I first implemented the OpenMP and Pthread branches....
