### ISSUE TITLE
"get_node()" API Consistency

### ISSUE THREAD

**Issue by friedmud** [libMesh/libmesh#889]
This has driven me crazy for years... can we fix this?  Obviously, it's API breakage... so I know it won't get fixed soon... but I just want to "get it on the docket" for fixing at some point.

Look at these accessors in `Mesh`:

```C++
virtual const Point & 	point (const dof_id_type i) const libmesh_override 
virtual const Node & 	node (const dof_id_type i) const libmesh_override
virtual Node & 	node (const dof_id_type i) libmesh_override
virtual const Node * 	node_ptr (const dof_id_type i) const libmesh_override
virtual Node * 	node_ptr (const dof_id_type i) libmesh_override
```

Now look at them in `Elem`:

```C++
dof_id_type 	node (const unsigned int i) const
Node * 	get_node (const unsigned int i) const
```

Note a few things:
  - `node()` in `Mesh` returns a `Node &` where it returns a `dof_id_type` in `Elem`!  Ah!!!! It drives me crazy... I can never remember which one to freaking call on which object.  I actually just had a bug that I lost about 15 minutes to because I called the wrong one and through an automatic cast of `dof_id_type` to `TypeVector` it was assigning the NODE ID as the x coordinate of a `Node`!  AAAAAAHHHHHHHH!!!!!!
  - For getting a pointer to a node `Mesh` uses `node_ptr()` where `Elem` uses `get_node()`.  Again, I can never remember which one is which!!

Personally: I think `Elem` is wrong.  The ones on `Mesh` make more sense to me.  Can we change `Elem` so that `Elem::node()` returns a `Node &` and rename `Elem::get_node()` to `Elem::node_ptr()` so we can have some consistency!

Ok - just had to vent... but wanted that venting to get captured so that one day we have some hope of fixing this :smile:

**Comment by permcody** [comment]
I always figured the difference was because `Elem` doesn't actually store the `Node` object. Yes, you could create a method that calls through to the Mesh to get the object but the Node just gives you what it has (i.e. the dofs).

Were you using `auto` by chance :wink:?

**Comment by friedmud** [comment]
Ass!  lol!

I was NOT using auto.  Try this:

```C++
mesh.add_point(elem->node(0));
```

It will happily assign a node id as the x position of that new node in this other mesh.  Handy! :imp: 

Your justification doesn't make sense... because `Elem` _does_ have `get_node()` which does return a `Node` already.

While we're at it... what's up the the weird inconsistency with getting `Elems` from `Mesh` also:

(All of this is in `Mesh`):
```C++
virtual Node & 	node (const dof_id_type i);
virtual Node * 	node_ptr (const dof_id_type i);
virtual Elem * 	elem (const dof_id_type i);
```

Why does `Mesh::node()` return a `Node &` while `Mesh::elem()` returns a pointer!  And there is no `Mesh::elem_ptr()` nor is there any way to get a `Elem &` back.  Just WTH.

I always knew these functions were all screwy... I _always_ have to go look at the Doxygen for them... even after 10+ years of using the library... but I never took the time to really look at why...

Can we fix this stuff... or is it "too big to fail" :hankey:

**Comment by roystgnr** [comment]
Not "too big to fail", but definitely "too old to fail" - there's no way to change these methods without breaking pretty much everybody's code, everywhere, in ways that would require intense effort to repair.

The only comparably huge change I can think of was when we added accessors for FEMContext members and made the members private... but that only affected a subset of libMesh codes, it only affected a class which IIRC was still libmesh_experimental() at the time, I wrote a script which was pretty decent at automating all the required changes in user code, and because the accessors had different names from the members we were able to provide a long transition period in between adding the former and removing the latter.

On the other hand... can we fix this stuff anyway?  If we were to give everything straightforward method names ("node_ptr", "node_ref", "elem_ptr", "elem_ref", "node_global_id"?) then we could keep the old names around indefinitely for backwards compatibility but we'd be able to use the new names in new code without having to hit the docs or trust our memories each time.

**Comment by jwpeterson** [comment]
> If we were to give everything straightforward method names ("node_ptr", "node_ref", "elem_ptr", "elem_ref", "node_global_id"?) 

This seems like it would work.  And I like these names. :+1:

**Comment by friedmud** [comment]
I like it!  Could we mark the old ones as deprecated at some point... and maybe in 20 years remove them?

Actually, it would be great to have a configure option that would turn off the old ones so they don't sneak into new code.  We would definitely fix all of these across MOOSE...

**Comment by friedmud** [comment]
To me this is along the same lines as CommWorld... we did that big change without too much crying...

**Comment by roystgnr** [comment]
I suppose we'd mark the old ones as deprecated immediately, add the configure option to disable them shortly after, make that option default after at least a year, remove them after at least 2.  The path we took for CommWorld was good, but there are a *lot* more uses of node() than there were of Parallel:: so I'd want to be more conservative about timing.

Would "node_id" be better than "node_global_id"?  Terser and I don't *think* it leaves room for confusion regardless.

**Comment by friedmud** [comment]
I like `node_id()`
