### ISSUE TITLE
Xdr format doesn't support shellfaces

### ISSUE THREAD

**Issue by dknez** [libMesh/libmesh#971]
A good way to test this is to change the start of miscellaneous_ex12 from:

```
  Mesh mesh (init.comm(), 3);
  mesh.read("cylinder.exo");
```

to:

```
  {
    Mesh mesh (init.comm(), 3);
    mesh.read("cylinder.exo");
    mesh.write("cylinder.xdr");
  }
  Mesh mesh (init.comm(), 3);
  mesh.read("cylinder.xdr");
```

I'd be happy to add a PR for this, but some guidance on what changes to make to XdrIO would be appreciated (@roystgnr, any thoughts on this?)

**Comment by roystgnr** [comment]
Well, my first thought is "we should have switched from custom-formats-built-on-XDR to custom-formats-built-on-HDF5 years ago, because it although it would have been four times as much work as any feature addition, it would have made every subsequent feature addition a fourth as much work".

But that's probably not what you're signing up for, so let's talk about doing things the easy way.

The first step is probably to factor out the "exceeds_version_foo" calculations.  Those shouldn't be in more than one place, because each time we have to bump the file format we risk missing one.

The second step would be to bump the file format version.  I guess this will be 1.1.0?

The last step would be to rename read/write_serialized_bcs to read/write_serialized_side_bcs, then add read/write_serialized_edge_bcs (yeah, that's been an outstanding bug for a while) and read/write_serialized_shellface_bcs in the same vein, making sure to only call the read versions when the file format version is high enough.

**Comment by dknez** [comment]
Yeah, I'll just go with the "easy way" for now :)

I just made PR #973. Let me know what you think.

**Comment by dknez** [comment]
#973 is merged now, which resolves this issue.
