### ISSUE TITLE
delete_remote_elements(DistributedMesh) deletes periodic neighbor elements

### ISSUE THREAD

**Issue by roystgnr** [libMesh/libmesh#977]
This triggers failures in some of the tests @pbauman and I are fixing up in https://github.com/grinsfem/grins/pull/408

Moving the discussion I'd started drafting there over to here where it's more appropriate:

Hmm... okay, I've figured out the segfault bug, and it'll be easy to get a more informative assert into libMesh to catch it before it reaches the segfault stage, but I've _no idea_ why I haven't managed to trigger it in the past, and I've no idea how best to fix it in either libMesh or GRINS.

When we load a ParallelMesh, the last thing we do is a prepare_for_use(), which among many other things deletes any remote elements from the mesh.  However, the definition of remote elements that it uses does not take periodic neighbors into account!

So there's three factors to the fix.

1) At the libMesh side, we need to move and/or copy some of the PeriodicBoundaries data from the DofMap into the Mesh; most of that data may be system-specific, but the Mesh needs to know what its own topology is.  We could do this with every add_periodic_boundary() call (perhaps checking first to see if the paired ids are already paired in an existing BC, in which case the Mesh is already aware of them), or we could do this en masse during the EquationSystems init.

2) At the libMesh side, we need to make sure that those periodic neighbors are treated as semilocal neighbors.  This is going to be a problem, because is_semilocal() thinks that it can figure out everything it needs to from neighbor links, but periodic neighbors (and point neighbors who meet at only one corner but aren't connected by a chain of other point neighbors, for that matter) don't qualify.  We can fix this easily enough in just the delete_local_elements() special case, but then what do we do when people relying on is_semilocal() and semilocal_elements_\* iterators don't end up hitting these trickier elements?

3a) At the application side, we need to make sure that the Mesh knows its own topology _before_ remote elements get deleted.  In other words, periodic boundaries need to get added either to a serialized Mesh or to a mesh that is already saving the periodic neighbor elements for some reason (because it was loaded from a parallel file that had been written in a periodic-boundary-aware state?)

3b) If we can't guarantee 3a (or don't want to, because that makes app developers lives too hard), then we could do a quick "serialize-then-distribute-again" step if libMesh detects that new periodic BCs have been added since the previous distribute.

3c) If we don't want to do 3b (because we're trying to get _rid_ of serialization after all) then we could add a gather_periodic_elements() method, similar to gather_neighboring_elements() but designed to get only those neighbors required for a new periodic BC.

I'm leaning toward 3c, due to it being the correct solution, but it's also the most tricky solution, and there's little chance I'll find time to finish it before July.

**Comment by friedmud** [comment]
@roystgnr I suggest a much more drastic change that is really needed: we need the ability to just flag elements (any element) as needing to be "ghosted" locally... and libMesh should just treat that element as if it's semilocal.  It should never get removed by `ParallelMesh` and its dofs should always be ghosted in all relevant ghosted vectors.

Basically: I want the ability to arbitrarily mark elements as needing to be treated just like the "one layer" of halo elements we always have.

This issue is not just relevant to periodic boundaries... it happens anytime you have a "gap" in the mesh and you want to keep elements on both sides of the gap for whatever reason.

For instance, in MOOSE this happens because of contact.  Because of that we have quite a bit of code to try to force libMesh into not deleting elements and ghosting those extra degrees of freedom.  To deal with this we have a few things:

1.  `ghosted_boundaries`.  This is an input file parameter that a user can supply that will cause any elements connected to those sidesets to be ghosted to _all_ processors (definitely non-optimal and heavy handed but it works for periodic and for contact boundaries).  You can see the code that does the ghosting here:

  https://github.com/idaholab/moose/blob/devel/framework/src/mesh/MooseMesh.C#L2116

2.  A couple of years ago I added `libMesh::DistributedMesh::add_extra_ghost_elem()` that at least tries to mark elements so that they won't be removed.  That function is here:
  https://github.com/libMesh/libmesh/blob/master/src/mesh/parallel_mesh.C#L1415

  And you can see the extra code _not_ remove the elems flagged this way here:

  https://github.com/libMesh/libmesh/blob/master/src/mesh/mesh_communication.C#L1349

3.  We do a LOT of work in MOOSE to try to make sure the dofs on these "extra ghost elems" end up in ghosted vectors.  It starts by keeping track of them here:
  https://github.com/idaholab/moose/blob/devel/framework/src/base/FEProblem.C#L913

  And then adding any dofs connected to those elements to the `send_list` here:

  https://github.com/idaholab/moose/blob/devel/framework/src/base/SystemBase.C#L377

4.  We have to do several `EquationSystem::reinit()` calls because of ghosted elements... we have to do one for adaptivity... and then another one after we re-adjust the ghosted elements (to get the vector ghosting right).  You can see that here:
  https://github.com/idaholab/moose/blob/devel/framework/src/base/FEProblem.C#L3761
  (Notice that above that is an `_eq.reinit()` which is the original `reinit()` call... and then the geometric search system might find more ghosted elements so we need to `reinit()` again to deal with them)

There is even more stuff in MOOSE to try do deal with "extra ghosted elems" but I think I've made my point: we need a unified way of dealing with this issue at the libMesh level.

In addition to the MOOSE stuff I have a new application where I want more than _one_ layer of ghosted "halo" elements.  I would like to be able to specify an arbitrary depth... and even if libMesh couldn't do that automatically... if I could run through the mesh and do that search myself and flag all the extra elements that need to be ghosted that would be a godsend.

Here's what I would like: one single place where each processor can register elements that need to be ghosted locally... and then everything else is automatically taken care of... they won't be removed by `delete_remote_elems()` and their dofs will automatically get added to the send list when vectors are reinitialized etc...

We need to get away from the idea that the only ghosting we want to do is a single layer of "bordering" elements.  The idea of a "ghosted element" needs to be a "first class" idea in libMesh...

**Comment by roystgnr** [comment]
We've wanted to do that for a long time... and I guess if we have to make major library changes to fix this bug *anyway*, then we might as well make the *right* major library changes.

If anyone has ideas about APIs, now's the time to brainstorm, then.

**Comment by roystgnr** [comment]
The DefaultCoupling ghosting functor now pays attention to periodic boundaries and ensures that periodic neighbors are kept semilocal.
